// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredBlocks = `-- name: CleanupExpiredBlocks :exec
UPDATE blocks SET
    is_active = false
WHERE is_active = true
  AND expires_at < NOW()
`

func (q *Queries) CleanupExpiredBlocks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredBlocks)
	return err
}

const countActiveBlocks = `-- name: CountActiveBlocks :one
SELECT COUNT(*) FROM blocks
WHERE user_id = $1 AND is_active = true
`

func (q *Queries) CountActiveBlocks(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveBlocks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBlocks = `-- name: CountBlocks :one
SELECT COUNT(*) FROM blocks
WHERE user_id = $1
`

func (q *Queries) CountBlocks(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBlocks, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBlocksToday = `-- name: CountBlocksToday :one
SELECT COUNT(*) FROM blocks
WHERE user_id = $1 
  AND blocked_at >= DATE_TRUNC('day', NOW())
`

func (q *Queries) CountBlocksToday(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBlocksToday, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlock = `-- name: CreateBlock :one

INSERT INTO blocks (
    server_id,
    user_id,
    ip_address,
    ip_version,
    threat_score,
    threat_level,
    reasons,
    target_port,
    service_name,
    protocol,
    country_code,
    country_name,
    city,
    region,
    latitude,
    longitude,
    asn,
    asn_org,
    is_vpn,
    is_tor,
    is_datacenter,
    blocked_at,
    expires_at,
    duration_seconds,
    is_auto_blocked,
    agent_version,
    raw_metrics
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27
) RETURNING id, server_id, user_id, ip_address, ip_version, threat_score, threat_level, reasons, target_port, service_name, protocol, country_code, country_name, city, region, latitude, longitude, asn, asn_org, is_vpn, is_tor, is_datacenter, blocked_at, expires_at, duration_seconds, is_active, is_auto_blocked, unblocked_at, unblocked_by, unblock_reason, agent_version, raw_metrics, created_at, updated_at
`

type CreateBlockParams struct {
	ServerID        pgtype.UUID        `json:"server_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	IpAddress       netip.Addr         `json:"ip_address"`
	IpVersion       pgtype.Int4        `json:"ip_version"`
	ThreatScore     int32              `json:"threat_score"`
	ThreatLevel     string             `json:"threat_level"`
	Reasons         []string           `json:"reasons"`
	TargetPort      pgtype.Int4        `json:"target_port"`
	ServiceName     pgtype.Text        `json:"service_name"`
	Protocol        pgtype.Text        `json:"protocol"`
	CountryCode     pgtype.Text        `json:"country_code"`
	CountryName     pgtype.Text        `json:"country_name"`
	City            pgtype.Text        `json:"city"`
	Region          pgtype.Text        `json:"region"`
	Latitude        pgtype.Float8      `json:"latitude"`
	Longitude       pgtype.Float8      `json:"longitude"`
	Asn             pgtype.Int4        `json:"asn"`
	AsnOrg          pgtype.Text        `json:"asn_org"`
	IsVpn           pgtype.Bool        `json:"is_vpn"`
	IsTor           pgtype.Bool        `json:"is_tor"`
	IsDatacenter    pgtype.Bool        `json:"is_datacenter"`
	BlockedAt       pgtype.Timestamptz `json:"blocked_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	DurationSeconds int32              `json:"duration_seconds"`
	IsAutoBlocked   pgtype.Bool        `json:"is_auto_blocked"`
	AgentVersion    pgtype.Text        `json:"agent_version"`
	RawMetrics      []byte             `json:"raw_metrics"`
}

// Blocks queries for the dashboard and API
func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error) {
	row := q.db.QueryRow(ctx, createBlock,
		arg.ServerID,
		arg.UserID,
		arg.IpAddress,
		arg.IpVersion,
		arg.ThreatScore,
		arg.ThreatLevel,
		arg.Reasons,
		arg.TargetPort,
		arg.ServiceName,
		arg.Protocol,
		arg.CountryCode,
		arg.CountryName,
		arg.City,
		arg.Region,
		arg.Latitude,
		arg.Longitude,
		arg.Asn,
		arg.AsnOrg,
		arg.IsVpn,
		arg.IsTor,
		arg.IsDatacenter,
		arg.BlockedAt,
		arg.ExpiresAt,
		arg.DurationSeconds,
		arg.IsAutoBlocked,
		arg.AgentVersion,
		arg.RawMetrics,
	)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.IpAddress,
		&i.IpVersion,
		&i.ThreatScore,
		&i.ThreatLevel,
		&i.Reasons,
		&i.TargetPort,
		&i.ServiceName,
		&i.Protocol,
		&i.CountryCode,
		&i.CountryName,
		&i.City,
		&i.Region,
		&i.Latitude,
		&i.Longitude,
		&i.Asn,
		&i.AsnOrg,
		&i.IsVpn,
		&i.IsTor,
		&i.IsDatacenter,
		&i.BlockedAt,
		&i.ExpiresAt,
		&i.DurationSeconds,
		&i.IsActive,
		&i.IsAutoBlocked,
		&i.UnblockedAt,
		&i.UnblockedBy,
		&i.UnblockReason,
		&i.AgentVersion,
		&i.RawMetrics,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveBlockByIP = `-- name: GetActiveBlockByIP :one
SELECT id, server_id, user_id, ip_address, ip_version, threat_score, threat_level, reasons, target_port, service_name, protocol, country_code, country_name, city, region, latitude, longitude, asn, asn_org, is_vpn, is_tor, is_datacenter, blocked_at, expires_at, duration_seconds, is_active, is_auto_blocked, unblocked_at, unblocked_by, unblock_reason, agent_version, raw_metrics, created_at, updated_at FROM blocks
WHERE user_id = $1 
  AND ip_address = $2
  AND is_active = true
LIMIT 1
`

type GetActiveBlockByIPParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	IpAddress netip.Addr  `json:"ip_address"`
}

func (q *Queries) GetActiveBlockByIP(ctx context.Context, arg GetActiveBlockByIPParams) (Block, error) {
	row := q.db.QueryRow(ctx, getActiveBlockByIP, arg.UserID, arg.IpAddress)
	var i Block
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.IpAddress,
		&i.IpVersion,
		&i.ThreatScore,
		&i.ThreatLevel,
		&i.Reasons,
		&i.TargetPort,
		&i.ServiceName,
		&i.Protocol,
		&i.CountryCode,
		&i.CountryName,
		&i.City,
		&i.Region,
		&i.Latitude,
		&i.Longitude,
		&i.Asn,
		&i.AsnOrg,
		&i.IsVpn,
		&i.IsTor,
		&i.IsDatacenter,
		&i.BlockedAt,
		&i.ExpiresAt,
		&i.DurationSeconds,
		&i.IsActive,
		&i.IsAutoBlocked,
		&i.UnblockedAt,
		&i.UnblockedBy,
		&i.UnblockReason,
		&i.AgentVersion,
		&i.RawMetrics,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlockByID = `-- name: GetBlockByID :one
SELECT b.id, b.server_id, b.user_id, b.ip_address, b.ip_version, b.threat_score, b.threat_level, b.reasons, b.target_port, b.service_name, b.protocol, b.country_code, b.country_name, b.city, b.region, b.latitude, b.longitude, b.asn, b.asn_org, b.is_vpn, b.is_tor, b.is_datacenter, b.blocked_at, b.expires_at, b.duration_seconds, b.is_active, b.is_auto_blocked, b.unblocked_at, b.unblocked_by, b.unblock_reason, b.agent_version, b.raw_metrics, b.created_at, b.updated_at, s.hostname as server_name
FROM blocks b
JOIN servers s ON b.server_id = s.id
WHERE b.id = $1 AND b.user_id = $2
`

type GetBlockByIDParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetBlockByIDRow struct {
	ID              pgtype.UUID        `json:"id"`
	ServerID        pgtype.UUID        `json:"server_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	IpAddress       netip.Addr         `json:"ip_address"`
	IpVersion       pgtype.Int4        `json:"ip_version"`
	ThreatScore     int32              `json:"threat_score"`
	ThreatLevel     string             `json:"threat_level"`
	Reasons         []string           `json:"reasons"`
	TargetPort      pgtype.Int4        `json:"target_port"`
	ServiceName     pgtype.Text        `json:"service_name"`
	Protocol        pgtype.Text        `json:"protocol"`
	CountryCode     pgtype.Text        `json:"country_code"`
	CountryName     pgtype.Text        `json:"country_name"`
	City            pgtype.Text        `json:"city"`
	Region          pgtype.Text        `json:"region"`
	Latitude        pgtype.Float8      `json:"latitude"`
	Longitude       pgtype.Float8      `json:"longitude"`
	Asn             pgtype.Int4        `json:"asn"`
	AsnOrg          pgtype.Text        `json:"asn_org"`
	IsVpn           pgtype.Bool        `json:"is_vpn"`
	IsTor           pgtype.Bool        `json:"is_tor"`
	IsDatacenter    pgtype.Bool        `json:"is_datacenter"`
	BlockedAt       pgtype.Timestamptz `json:"blocked_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	DurationSeconds int32              `json:"duration_seconds"`
	IsActive        pgtype.Bool        `json:"is_active"`
	IsAutoBlocked   pgtype.Bool        `json:"is_auto_blocked"`
	UnblockedAt     pgtype.Timestamptz `json:"unblocked_at"`
	UnblockedBy     pgtype.UUID        `json:"unblocked_by"`
	UnblockReason   pgtype.Text        `json:"unblock_reason"`
	AgentVersion    pgtype.Text        `json:"agent_version"`
	RawMetrics      []byte             `json:"raw_metrics"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ServerName      string             `json:"server_name"`
}

func (q *Queries) GetBlockByID(ctx context.Context, arg GetBlockByIDParams) (GetBlockByIDRow, error) {
	row := q.db.QueryRow(ctx, getBlockByID, arg.ID, arg.UserID)
	var i GetBlockByIDRow
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.IpAddress,
		&i.IpVersion,
		&i.ThreatScore,
		&i.ThreatLevel,
		&i.Reasons,
		&i.TargetPort,
		&i.ServiceName,
		&i.Protocol,
		&i.CountryCode,
		&i.CountryName,
		&i.City,
		&i.Region,
		&i.Latitude,
		&i.Longitude,
		&i.Asn,
		&i.AsnOrg,
		&i.IsVpn,
		&i.IsTor,
		&i.IsDatacenter,
		&i.BlockedAt,
		&i.ExpiresAt,
		&i.DurationSeconds,
		&i.IsActive,
		&i.IsAutoBlocked,
		&i.UnblockedAt,
		&i.UnblockedBy,
		&i.UnblockReason,
		&i.AgentVersion,
		&i.RawMetrics,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ServerName,
	)
	return i, err
}

const getBlockRemainingTime = `-- name: GetBlockRemainingTime :one
SELECT EXTRACT(EPOCH FROM (expires_at - NOW()))::bigint as seconds
FROM blocks
WHERE user_id = $1 
  AND ip_address = $2
  AND is_active = true
`

type GetBlockRemainingTimeParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	IpAddress netip.Addr  `json:"ip_address"`
}

func (q *Queries) GetBlockRemainingTime(ctx context.Context, arg GetBlockRemainingTimeParams) (int64, error) {
	row := q.db.QueryRow(ctx, getBlockRemainingTime, arg.UserID, arg.IpAddress)
	var seconds int64
	err := row.Scan(&seconds)
	return seconds, err
}

const getBlockStatsByCountry = `-- name: GetBlockStatsByCountry :many
SELECT 
    COALESCE(country_code, 'unknown') as country_code,
    COUNT(*) as count
FROM blocks
WHERE user_id = $1
  AND blocked_at >= NOW() - INTERVAL '30 days'
GROUP BY country_code
ORDER BY count DESC
LIMIT 20
`

type GetBlockStatsByCountryRow struct {
	CountryCode string `json:"country_code"`
	Count       int64  `json:"count"`
}

func (q *Queries) GetBlockStatsByCountry(ctx context.Context, userID pgtype.UUID) ([]GetBlockStatsByCountryRow, error) {
	rows, err := q.db.Query(ctx, getBlockStatsByCountry, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlockStatsByCountryRow{}
	for rows.Next() {
		var i GetBlockStatsByCountryRow
		if err := rows.Scan(&i.CountryCode, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockStatsByServer = `-- name: GetBlockStatsByServer :many
SELECT 
    s.hostname as server_name,
    COUNT(*) as count
FROM blocks b
JOIN servers s ON b.server_id = s.id
WHERE b.user_id = $1
  AND b.blocked_at >= NOW() - INTERVAL '30 days'
GROUP BY s.hostname
ORDER BY count DESC
`

type GetBlockStatsByServerRow struct {
	ServerName string `json:"server_name"`
	Count      int64  `json:"count"`
}

func (q *Queries) GetBlockStatsByServer(ctx context.Context, userID pgtype.UUID) ([]GetBlockStatsByServerRow, error) {
	rows, err := q.db.Query(ctx, getBlockStatsByServer, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlockStatsByServerRow{}
	for rows.Next() {
		var i GetBlockStatsByServerRow
		if err := rows.Scan(&i.ServerName, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockStatsByService = `-- name: GetBlockStatsByService :many

SELECT 
    COALESCE(service_name, 'unknown') as service_name,
    COUNT(*) as count
FROM blocks
WHERE user_id = $1
  AND blocked_at >= NOW() - INTERVAL '30 days'
GROUP BY service_name
ORDER BY count DESC
`

type GetBlockStatsByServiceRow struct {
	ServiceName string `json:"service_name"`
	Count       int64  `json:"count"`
}

// Statistics queries
func (q *Queries) GetBlockStatsByService(ctx context.Context, userID pgtype.UUID) ([]GetBlockStatsByServiceRow, error) {
	rows, err := q.db.Query(ctx, getBlockStatsByService, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlockStatsByServiceRow{}
	for rows.Next() {
		var i GetBlockStatsByServiceRow
		if err := rows.Scan(&i.ServiceName, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlockStatsByThreatLevel = `-- name: GetBlockStatsByThreatLevel :many
SELECT 
    threat_level,
    COUNT(*) as count
FROM blocks
WHERE user_id = $1
  AND blocked_at >= NOW() - INTERVAL '30 days'
GROUP BY threat_level
ORDER BY count DESC
`

type GetBlockStatsByThreatLevelRow struct {
	ThreatLevel string `json:"threat_level"`
	Count       int64  `json:"count"`
}

func (q *Queries) GetBlockStatsByThreatLevel(ctx context.Context, userID pgtype.UUID) ([]GetBlockStatsByThreatLevelRow, error) {
	rows, err := q.db.Query(ctx, getBlockStatsByThreatLevel, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetBlockStatsByThreatLevelRow{}
	for rows.Next() {
		var i GetBlockStatsByThreatLevelRow
		if err := rows.Scan(&i.ThreatLevel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentBlocks = `-- name: GetRecentBlocks :many
SELECT 
    b.id, b.server_id, b.user_id, b.ip_address, b.ip_version, b.threat_score, b.threat_level, b.reasons, b.target_port, b.service_name, b.protocol, b.country_code, b.country_name, b.city, b.region, b.latitude, b.longitude, b.asn, b.asn_org, b.is_vpn, b.is_tor, b.is_datacenter, b.blocked_at, b.expires_at, b.duration_seconds, b.is_active, b.is_auto_blocked, b.unblocked_at, b.unblocked_by, b.unblock_reason, b.agent_version, b.raw_metrics, b.created_at, b.updated_at,
    s.hostname as server_name
FROM blocks b
JOIN servers s ON b.server_id = s.id
WHERE b.user_id = $1
ORDER BY b.blocked_at DESC
LIMIT $2
`

type GetRecentBlocksParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type GetRecentBlocksRow struct {
	ID              pgtype.UUID        `json:"id"`
	ServerID        pgtype.UUID        `json:"server_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	IpAddress       netip.Addr         `json:"ip_address"`
	IpVersion       pgtype.Int4        `json:"ip_version"`
	ThreatScore     int32              `json:"threat_score"`
	ThreatLevel     string             `json:"threat_level"`
	Reasons         []string           `json:"reasons"`
	TargetPort      pgtype.Int4        `json:"target_port"`
	ServiceName     pgtype.Text        `json:"service_name"`
	Protocol        pgtype.Text        `json:"protocol"`
	CountryCode     pgtype.Text        `json:"country_code"`
	CountryName     pgtype.Text        `json:"country_name"`
	City            pgtype.Text        `json:"city"`
	Region          pgtype.Text        `json:"region"`
	Latitude        pgtype.Float8      `json:"latitude"`
	Longitude       pgtype.Float8      `json:"longitude"`
	Asn             pgtype.Int4        `json:"asn"`
	AsnOrg          pgtype.Text        `json:"asn_org"`
	IsVpn           pgtype.Bool        `json:"is_vpn"`
	IsTor           pgtype.Bool        `json:"is_tor"`
	IsDatacenter    pgtype.Bool        `json:"is_datacenter"`
	BlockedAt       pgtype.Timestamptz `json:"blocked_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	DurationSeconds int32              `json:"duration_seconds"`
	IsActive        pgtype.Bool        `json:"is_active"`
	IsAutoBlocked   pgtype.Bool        `json:"is_auto_blocked"`
	UnblockedAt     pgtype.Timestamptz `json:"unblocked_at"`
	UnblockedBy     pgtype.UUID        `json:"unblocked_by"`
	UnblockReason   pgtype.Text        `json:"unblock_reason"`
	AgentVersion    pgtype.Text        `json:"agent_version"`
	RawMetrics      []byte             `json:"raw_metrics"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ServerName      string             `json:"server_name"`
}

func (q *Queries) GetRecentBlocks(ctx context.Context, arg GetRecentBlocksParams) ([]GetRecentBlocksRow, error) {
	rows, err := q.db.Query(ctx, getRecentBlocks, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentBlocksRow{}
	for rows.Next() {
		var i GetRecentBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.UserID,
			&i.IpAddress,
			&i.IpVersion,
			&i.ThreatScore,
			&i.ThreatLevel,
			&i.Reasons,
			&i.TargetPort,
			&i.ServiceName,
			&i.Protocol,
			&i.CountryCode,
			&i.CountryName,
			&i.City,
			&i.Region,
			&i.Latitude,
			&i.Longitude,
			&i.Asn,
			&i.AsnOrg,
			&i.IsVpn,
			&i.IsTor,
			&i.IsDatacenter,
			&i.BlockedAt,
			&i.ExpiresAt,
			&i.DurationSeconds,
			&i.IsActive,
			&i.IsAutoBlocked,
			&i.UnblockedAt,
			&i.UnblockedBy,
			&i.UnblockReason,
			&i.AgentVersion,
			&i.RawMetrics,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isIPBlocked = `-- name: IsIPBlocked :one
SELECT EXISTS(
    SELECT 1 FROM blocks
    WHERE user_id = $1 
      AND ip_address = $2
      AND is_active = true
)
`

type IsIPBlockedParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	IpAddress netip.Addr  `json:"ip_address"`
}

func (q *Queries) IsIPBlocked(ctx context.Context, arg IsIPBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isIPBlocked, arg.UserID, arg.IpAddress)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listBlocks = `-- name: ListBlocks :many
SELECT 
    b.id, b.server_id, b.user_id, b.ip_address, b.ip_version, b.threat_score, b.threat_level, b.reasons, b.target_port, b.service_name, b.protocol, b.country_code, b.country_name, b.city, b.region, b.latitude, b.longitude, b.asn, b.asn_org, b.is_vpn, b.is_tor, b.is_datacenter, b.blocked_at, b.expires_at, b.duration_seconds, b.is_active, b.is_auto_blocked, b.unblocked_at, b.unblocked_by, b.unblock_reason, b.agent_version, b.raw_metrics, b.created_at, b.updated_at,
    s.hostname as server_name
FROM blocks b
JOIN servers s ON b.server_id = s.id
WHERE b.user_id = $1
  AND (b.server_id = $2 OR $2 IS NULL)
  AND (b.service_name = $3 OR $3 IS NULL)
  AND (b.country_code = $4 OR $4 IS NULL)
  AND (b.is_active = $5 OR $5 IS NULL)
  AND (
      ($6 = false AND b.unblocked_at IS NULL)
      OR ($6 = true AND b.unblocked_at IS NOT NULL)
      OR $6 IS NULL
  )
  AND (b.ip_address::text LIKE '%' || $7 || '%' OR $7 IS NULL)
ORDER BY b.blocked_at DESC
LIMIT $8 OFFSET $9
`

type ListBlocksParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	ServerID    pgtype.UUID `json:"server_id"`
	ServiceName pgtype.Text `json:"service_name"`
	CountryCode pgtype.Text `json:"country_code"`
	IsActive    pgtype.Bool `json:"is_active"`
	Column6     interface{} `json:"column_6"`
	Column7     pgtype.Text `json:"column_7"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

type ListBlocksRow struct {
	ID              pgtype.UUID        `json:"id"`
	ServerID        pgtype.UUID        `json:"server_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	IpAddress       netip.Addr         `json:"ip_address"`
	IpVersion       pgtype.Int4        `json:"ip_version"`
	ThreatScore     int32              `json:"threat_score"`
	ThreatLevel     string             `json:"threat_level"`
	Reasons         []string           `json:"reasons"`
	TargetPort      pgtype.Int4        `json:"target_port"`
	ServiceName     pgtype.Text        `json:"service_name"`
	Protocol        pgtype.Text        `json:"protocol"`
	CountryCode     pgtype.Text        `json:"country_code"`
	CountryName     pgtype.Text        `json:"country_name"`
	City            pgtype.Text        `json:"city"`
	Region          pgtype.Text        `json:"region"`
	Latitude        pgtype.Float8      `json:"latitude"`
	Longitude       pgtype.Float8      `json:"longitude"`
	Asn             pgtype.Int4        `json:"asn"`
	AsnOrg          pgtype.Text        `json:"asn_org"`
	IsVpn           pgtype.Bool        `json:"is_vpn"`
	IsTor           pgtype.Bool        `json:"is_tor"`
	IsDatacenter    pgtype.Bool        `json:"is_datacenter"`
	BlockedAt       pgtype.Timestamptz `json:"blocked_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	DurationSeconds int32              `json:"duration_seconds"`
	IsActive        pgtype.Bool        `json:"is_active"`
	IsAutoBlocked   pgtype.Bool        `json:"is_auto_blocked"`
	UnblockedAt     pgtype.Timestamptz `json:"unblocked_at"`
	UnblockedBy     pgtype.UUID        `json:"unblocked_by"`
	UnblockReason   pgtype.Text        `json:"unblock_reason"`
	AgentVersion    pgtype.Text        `json:"agent_version"`
	RawMetrics      []byte             `json:"raw_metrics"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	ServerName      string             `json:"server_name"`
}

func (q *Queries) ListBlocks(ctx context.Context, arg ListBlocksParams) ([]ListBlocksRow, error) {
	rows, err := q.db.Query(ctx, listBlocks,
		arg.UserID,
		arg.ServerID,
		arg.ServiceName,
		arg.CountryCode,
		arg.IsActive,
		arg.Column6,
		arg.Column7,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlocksRow{}
	for rows.Next() {
		var i ListBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.UserID,
			&i.IpAddress,
			&i.IpVersion,
			&i.ThreatScore,
			&i.ThreatLevel,
			&i.Reasons,
			&i.TargetPort,
			&i.ServiceName,
			&i.Protocol,
			&i.CountryCode,
			&i.CountryName,
			&i.City,
			&i.Region,
			&i.Latitude,
			&i.Longitude,
			&i.Asn,
			&i.AsnOrg,
			&i.IsVpn,
			&i.IsTor,
			&i.IsDatacenter,
			&i.BlockedAt,
			&i.ExpiresAt,
			&i.DurationSeconds,
			&i.IsActive,
			&i.IsAutoBlocked,
			&i.UnblockedAt,
			&i.UnblockedBy,
			&i.UnblockReason,
			&i.AgentVersion,
			&i.RawMetrics,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unblockIP = `-- name: UnblockIP :exec
UPDATE blocks SET
    is_active = false,
    unblocked_at = $2,
    unblocked_by = $3,
    unblock_reason = $4,
    updated_at = NOW()
WHERE id = $1
`

type UnblockIPParams struct {
	ID            pgtype.UUID        `json:"id"`
	UnblockedAt   pgtype.Timestamptz `json:"unblocked_at"`
	UnblockedBy   pgtype.UUID        `json:"unblocked_by"`
	UnblockReason pgtype.Text        `json:"unblock_reason"`
}

func (q *Queries) UnblockIP(ctx context.Context, arg UnblockIPParams) error {
	_, err := q.db.Exec(ctx, unblockIP,
		arg.ID,
		arg.UnblockedAt,
		arg.UnblockedBy,
		arg.UnblockReason,
	)
	return err
}

const updateBlockExpiry = `-- name: UpdateBlockExpiry :exec
UPDATE blocks SET
    expires_at = $2,
    blocked_at = COALESCE($3, blocked_at),
    duration_seconds = COALESCE($4, duration_seconds),
    updated_at = NOW()
WHERE id = $1
`

type UpdateBlockExpiryParams struct {
	ID              pgtype.UUID        `json:"id"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	BlockedAt       pgtype.Timestamptz `json:"blocked_at"`
	DurationSeconds int32              `json:"duration_seconds"`
}

func (q *Queries) UpdateBlockExpiry(ctx context.Context, arg UpdateBlockExpiryParams) error {
	_, err := q.db.Exec(ctx, updateBlockExpiry,
		arg.ID,
		arg.ExpiresAt,
		arg.BlockedAt,
		arg.DurationSeconds,
	)
	return err
}

const updateServerMetadata = `-- name: UpdateServerMetadata :exec
UPDATE servers SET
    metadata = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateServerMetadataParams struct {
	ID       pgtype.UUID `json:"id"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) UpdateServerMetadata(ctx context.Context, arg UpdateServerMetadataParams) error {
	_, err := q.db.Exec(ctx, updateServerMetadata, arg.ID, arg.Metadata)
	return err
}
