// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

// Threat alerts triggered by scoring system
type Alert struct {
	ID             pgtype.UUID        `json:"id"`
	ServerID       pgtype.UUID        `json:"server_id"`
	SourceIp       netip.Addr         `json:"source_ip"`
	ThreatScore    int32              `json:"threat_score"`
	Reason         string             `json:"reason"`
	Severity       string             `json:"severity"`
	Status         string             `json:"status"`
	AutoBlocked    pgtype.Bool        `json:"auto_blocked"`
	BlockedUntil   pgtype.Timestamptz `json:"blocked_until"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
}

// User action audit trail
type AuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Action       string             `json:"action"`
	ResourceType pgtype.Text        `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	Metadata     []byte             `json:"metadata"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// IPs to block or allow (Phase 2)
type BlockList struct {
	ID        pgtype.UUID        `json:"id"`
	ServerID  pgtype.UUID        `json:"server_id"`
	IpAddress netip.Addr         `json:"ip_address"`
	Action    string             `json:"action"`
	Reason    pgtype.Text        `json:"reason"`
	AutoAdded pgtype.Bool        `json:"auto_added"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	CreatedBy pgtype.UUID        `json:"created_by"`
}

// Daily aggregated statistics per IP address
type IpStat struct {
	ID                    pgtype.UUID        `json:"id"`
	ServerID              pgtype.UUID        `json:"server_id"`
	SourceIp              netip.Addr         `json:"source_ip"`
	Date                  pgtype.Date        `json:"date"`
	TotalConnections      int32              `json:"total_connections"`
	TotalSyn              int32              `json:"total_syn"`
	TotalAck              int32              `json:"total_ack"`
	TotalFailedHandshakes int32              `json:"total_failed_handshakes"`
	MaxThreatScore        int32              `json:"max_threat_score"`
	UniquePortsCount      int32              `json:"unique_ports_count"`
	TotalBytesIn          int64              `json:"total_bytes_in"`
	TotalBytesOut         int64              `json:"total_bytes_out"`
	CountryCode           pgtype.Text        `json:"country_code"`
	City                  pgtype.Text        `json:"city"`
	Asn                   pgtype.Int4        `json:"asn"`
	AsnOrg                pgtype.Text        `json:"asn_org"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// Monitored servers with agent installations
type Server struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Hostname     string             `json:"hostname"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	ApiKey       pgtype.Text        `json:"api_key"`
	Status       string             `json:"status"`
	LastSeen     pgtype.Timestamptz `json:"last_seen"`
	AgentVersion pgtype.Text        `json:"agent_version"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ClientToken  pgtype.Text        `json:"client_token"`
}

// Webhook events from Polar for audit trail
type SubscriptionEvent struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	PolarEventID pgtype.Text        `json:"polar_event_id"`
	EventType    string             `json:"event_type"`
	Payload      []byte             `json:"payload"`
	Processed    pgtype.Bool        `json:"processed"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Available subscription plans with Polar integration. Set polar_price_id after creating products in Polar dashboard
type SubscriptionPlan struct {
	ID                pgtype.UUID        `json:"id"`
	Name              string             `json:"name"`
	DisplayName       string             `json:"display_name"`
	Description       pgtype.Text        `json:"description"`
	PriceCents        int32              `json:"price_cents"`
	Currency          pgtype.Text        `json:"currency"`
	BillingInterval   string             `json:"billing_interval"`
	MaxServers        int32              `json:"max_servers"`
	DataRetentionDays int32              `json:"data_retention_days"`
	Features          []byte             `json:"features"`
	PolarProductID    pgtype.Text        `json:"polar_product_id"`
	PolarPriceID      pgtype.Text        `json:"polar_price_id"`
	IsActive          pgtype.Bool        `json:"is_active"`
	IsDefault         pgtype.Bool        `json:"is_default"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

// Aggregated network traffic events from agents
type TrafficEvent struct {
	ID               pgtype.UUID        `json:"id"`
	ServerID         pgtype.UUID        `json:"server_id"`
	SourceIp         netip.Addr         `json:"source_ip"`
	DestinationPort  int32              `json:"destination_port"`
	Protocol         string             `json:"protocol"`
	SynCount         int32              `json:"syn_count"`
	AckCount         int32              `json:"ack_count"`
	FailedHandshakes int32              `json:"failed_handshakes"`
	UniquePorts      int32              `json:"unique_ports"`
	BytesIn          int64              `json:"bytes_in"`
	BytesOut         int64              `json:"bytes_out"`
	ThreatScore      int32              `json:"threat_score"`
	ThreatLevel      string             `json:"threat_level"`
	FirstSeen        pgtype.Timestamptz `json:"first_seen"`
	LastSeen         pgtype.Timestamptz `json:"last_seen"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Country          pgtype.Text        `json:"country"`
	City             pgtype.Text        `json:"city"`
	Isp              pgtype.Text        `json:"isp"`
	HitCount         int32              `json:"hit_count"`
	Direction        string             `json:"direction"`
	DestinationIp    *netip.Addr        `json:"destination_ip"`
	Asn              pgtype.Text        `json:"asn"`
}

// KernelEye customer accounts
type User struct {
	ID                             pgtype.UUID        `json:"id"`
	Email                          string             `json:"email"`
	PasswordHash                   string             `json:"password_hash"`
	Plan                           string             `json:"plan"`
	MaxServers                     int32              `json:"max_servers"`
	StripeCustomerID               pgtype.Text        `json:"stripe_customer_id"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                      pgtype.Timestamptz `json:"updated_at"`
	PolarCustomerID                pgtype.Text        `json:"polar_customer_id"`
	PolarSubscriptionID            pgtype.Text        `json:"polar_subscription_id"`
	SubscriptionStatus             pgtype.Text        `json:"subscription_status"`
	SubscriptionCurrentPeriodStart pgtype.Timestamptz `json:"subscription_current_period_start"`
	SubscriptionCurrentPeriodEnd   pgtype.Timestamptz `json:"subscription_current_period_end"`
	SubscriptionCancelAtPeriodEnd  pgtype.Bool        `json:"subscription_cancel_at_period_end"`
	TrialEndsAt                    pgtype.Timestamptz `json:"trial_ends_at"`
}

// Convenience view of user subscription status
type UserSubscription struct {
	UserID                         pgtype.UUID        `json:"user_id"`
	Email                          string             `json:"email"`
	Plan                           string             `json:"plan"`
	SubscriptionStatus             pgtype.Text        `json:"subscription_status"`
	MaxServers                     int32              `json:"max_servers"`
	SubscriptionCurrentPeriodStart pgtype.Timestamptz `json:"subscription_current_period_start"`
	SubscriptionCurrentPeriodEnd   pgtype.Timestamptz `json:"subscription_current_period_end"`
	SubscriptionCancelAtPeriodEnd  pgtype.Bool        `json:"subscription_cancel_at_period_end"`
	TrialEndsAt                    pgtype.Timestamptz `json:"trial_ends_at"`
	PlanDisplayName                pgtype.Text        `json:"plan_display_name"`
	PriceCents                     pgtype.Int4        `json:"price_cents"`
	DataRetentionDays              pgtype.Int4        `json:"data_retention_days"`
	Features                       []byte             `json:"features"`
	CurrentServerCount             int64              `json:"current_server_count"`
}
