// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

// Threat alerts triggered by scoring system
type Alert struct {
	ID             pgtype.UUID        `json:"id"`
	ServerID       pgtype.UUID        `json:"server_id"`
	SourceIp       netip.Addr         `json:"source_ip"`
	ThreatScore    int32              `json:"threat_score"`
	Reason         string             `json:"reason"`
	Severity       string             `json:"severity"`
	Status         string             `json:"status"`
	AutoBlocked    pgtype.Bool        `json:"auto_blocked"`
	BlockedUntil   pgtype.Timestamptz `json:"blocked_until"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
}

// IP blocks reported by agents with threat details and GeoIP
type Block struct {
	ID          pgtype.UUID `json:"id"`
	ServerID    pgtype.UUID `json:"server_id"`
	UserID      pgtype.UUID `json:"user_id"`
	IpAddress   netip.Addr  `json:"ip_address"`
	IpVersion   pgtype.Int4 `json:"ip_version"`
	ThreatScore int32       `json:"threat_score"`
	ThreatLevel string      `json:"threat_level"`
	Reasons     []string    `json:"reasons"`
	TargetPort  pgtype.Int4 `json:"target_port"`
	// Detected service based on target port (ssh, http, https, etc.)
	ServiceName pgtype.Text   `json:"service_name"`
	Protocol    pgtype.Text   `json:"protocol"`
	CountryCode pgtype.Text   `json:"country_code"`
	CountryName pgtype.Text   `json:"country_name"`
	City        pgtype.Text   `json:"city"`
	Region      pgtype.Text   `json:"region"`
	Latitude    pgtype.Float8 `json:"latitude"`
	Longitude   pgtype.Float8 `json:"longitude"`
	Asn         pgtype.Int4   `json:"asn"`
	AsnOrg      pgtype.Text   `json:"asn_org"`
	IsVpn       pgtype.Bool   `json:"is_vpn"`
	IsTor       pgtype.Bool   `json:"is_tor"`
	// TRUE if IP is from known cloud provider (AWS, GCP, etc.)
	IsDatacenter pgtype.Bool        `json:"is_datacenter"`
	BlockedAt    pgtype.Timestamptz `json:"blocked_at"`
	// Block expiration time. NULL = permanent block (no expiry).
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	DurationSeconds int32              `json:"duration_seconds"`
	IsActive        pgtype.Bool        `json:"is_active"`
	IsAutoBlocked   pgtype.Bool        `json:"is_auto_blocked"`
	UnblockedAt     pgtype.Timestamptz `json:"unblocked_at"`
	UnblockedBy     pgtype.UUID        `json:"unblocked_by"`
	UnblockReason   pgtype.Text        `json:"unblock_reason"`
	AgentVersion    pgtype.Text        `json:"agent_version"`
	RawMetrics      []byte             `json:"raw_metrics"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	EnforcementType string             `json:"enforcement_type"`
}

type BlockStatsDaily struct {
	UserID          pgtype.UUID `json:"user_id"`
	ServerID        pgtype.UUID `json:"server_id"`
	Date            pgtype.Date `json:"date"`
	TotalBlocks     int64       `json:"total_blocks"`
	ActiveBlocks    int64       `json:"active_blocks"`
	CriticalBlocks  int64       `json:"critical_blocks"`
	UniqueIps       int64       `json:"unique_ips"`
	UniqueCountries int64       `json:"unique_countries"`
	SshAttacks      int64       `json:"ssh_attacks"`
	HttpAttacks     int64       `json:"http_attacks"`
	HttpsAttacks    int64       `json:"https_attacks"`
	AvgScore        float64     `json:"avg_score"`
	MaxScore        interface{} `json:"max_score"`
}

type MonthlyReportsSent struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ReportMonth pgtype.Date        `json:"report_month"`
	SentAt      pgtype.Timestamptz `json:"sent_at"`
}

// Monitored servers with agent installations
type Server struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Hostname     string             `json:"hostname"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	ApiKey       pgtype.Text        `json:"api_key"`
	Status       string             `json:"status"`
	LastSeen     pgtype.Timestamptz `json:"last_seen"`
	AgentVersion pgtype.Text        `json:"agent_version"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ClientToken  pgtype.Text        `json:"client_token"`
	Config       []byte             `json:"config"`
}

// Aggregated network traffic events from agents
type TrafficEvent struct {
	ID                   pgtype.UUID        `json:"id"`
	ServerID             pgtype.UUID        `json:"server_id"`
	SourceIp             netip.Addr         `json:"source_ip"`
	DestinationPort      int32              `json:"destination_port"`
	Protocol             string             `json:"protocol"`
	SynCount             int32              `json:"syn_count"`
	AckCount             int32              `json:"ack_count"`
	FailedHandshakes     int32              `json:"failed_handshakes"`
	UniquePorts          int32              `json:"unique_ports"`
	BytesIn              int64              `json:"bytes_in"`
	BytesOut             int64              `json:"bytes_out"`
	ThreatScore          int32              `json:"threat_score"`
	ThreatLevel          string             `json:"threat_level"`
	FirstSeen            pgtype.Timestamptz `json:"first_seen"`
	LastSeen             pgtype.Timestamptz `json:"last_seen"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	Country              pgtype.Text        `json:"country"`
	City                 pgtype.Text        `json:"city"`
	Isp                  pgtype.Text        `json:"isp"`
	HitCount             int32              `json:"hit_count"`
	Direction            string             `json:"direction"`
	DestinationIp        *netip.Addr        `json:"destination_ip"`
	Asn                  pgtype.Text        `json:"asn"`
	ThreatType           pgtype.Text        `json:"threat_type"`
	CountryCode          pgtype.Text        `json:"country_code"`
	IcmpPacketsIn        int64              `json:"icmp_packets_in"`
	IcmpPacketsOut       int64              `json:"icmp_packets_out"`
	ConnectionDurationMs int64              `json:"connection_duration_ms"`
	PortBytesIn          []byte             `json:"port_bytes_in"`
	PortBytesOut         []byte             `json:"port_bytes_out"`
	ServiceName          string             `json:"service_name"`
}

type TrafficEventsArchive struct {
	ID                   pgtype.UUID        `json:"id"`
	ServerID             pgtype.UUID        `json:"server_id"`
	SourceIp             netip.Addr         `json:"source_ip"`
	DestinationPort      pgtype.Int4        `json:"destination_port"`
	Protocol             pgtype.Text        `json:"protocol"`
	Direction            pgtype.Text        `json:"direction"`
	BytesIn              pgtype.Int8        `json:"bytes_in"`
	BytesOut             pgtype.Int8        `json:"bytes_out"`
	HitCount             pgtype.Int4        `json:"hit_count"`
	SynCount             pgtype.Int4        `json:"syn_count"`
	AckCount             pgtype.Int4        `json:"ack_count"`
	FailedHandshakes     pgtype.Int4        `json:"failed_handshakes"`
	ThreatScore          pgtype.Int4        `json:"threat_score"`
	ThreatLevel          pgtype.Text        `json:"threat_level"`
	ThreatType           pgtype.Text        `json:"threat_type"`
	Country              pgtype.Text        `json:"country"`
	CountryCode          pgtype.Text        `json:"country_code"`
	City                 pgtype.Text        `json:"city"`
	Isp                  pgtype.Text        `json:"isp"`
	Asn                  pgtype.Text        `json:"asn"`
	FirstSeen            pgtype.Timestamptz `json:"first_seen"`
	LastSeen             pgtype.Timestamptz `json:"last_seen"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	ArchivedAt           pgtype.Timestamptz `json:"archived_at"`
	IcmpPacketsIn        pgtype.Int8        `json:"icmp_packets_in"`
	IcmpPacketsOut       pgtype.Int8        `json:"icmp_packets_out"`
	ConnectionDurationMs pgtype.Int8        `json:"connection_duration_ms"`
	PortBytesIn          []byte             `json:"port_bytes_in"`
	PortBytesOut         []byte             `json:"port_bytes_out"`
}

type TrafficTimeline struct {
	ServerID         pgtype.UUID        `json:"server_id"`
	SourceIp         netip.Addr         `json:"source_ip"`
	Bucket           pgtype.Timestamptz `json:"bucket"`
	HitCount         int32              `json:"hit_count"`
	SynCount         int32              `json:"syn_count"`
	AckCount         int32              `json:"ack_count"`
	FailedHandshakes int32              `json:"failed_handshakes"`
	BytesIn          int64              `json:"bytes_in"`
	BytesOut         int64              `json:"bytes_out"`
	ThreatScore      int32              `json:"threat_score"`
}

// KernelEye user accounts
type User struct {
	ID                    pgtype.UUID        `json:"id"`
	Email                 string             `json:"email"`
	PasswordHash          string             `json:"password_hash"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
}

// Whitelisted IPs that should never be blocked
type Whitelist struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	IpAddress netip.Addr         `json:"ip_address"`
	IpVersion int32              `json:"ip_version"`
	Reason    pgtype.Text        `json:"reason"`
	IsManual  bool               `json:"is_manual"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
