// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (
    server_id, source_ip, threat_score, reason, 
    severity, status, auto_blocked
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, server_id, source_ip, threat_score, reason, severity, status, auto_blocked, blocked_until, created_at, acknowledged_at, resolved_at
`

type CreateAlertParams struct {
	ServerID    pgtype.UUID `json:"server_id"`
	SourceIp    netip.Addr  `json:"source_ip"`
	ThreatScore int32       `json:"threat_score"`
	Reason      string      `json:"reason"`
	Severity    string      `json:"severity"`
	Status      string      `json:"status"`
	AutoBlocked pgtype.Bool `json:"auto_blocked"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.ServerID,
		arg.SourceIp,
		arg.ThreatScore,
		arg.Reason,
		arg.Severity,
		arg.Status,
		arg.AutoBlocked,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.SourceIp,
		&i.ThreatScore,
		&i.Reason,
		&i.Severity,
		&i.Status,
		&i.AutoBlocked,
		&i.BlockedUntil,
		&i.CreatedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const createServer = `-- name: CreateServer :one
INSERT INTO servers (user_id, hostname, api_key, last_seen)
VALUES ($1, $2, $3, NOW())
RETURNING id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token
`

type CreateServerParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Hostname string      `json:"hostname"`
	ApiKey   pgtype.Text `json:"api_key"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer, arg.UserID, arg.Hostname, arg.ApiKey)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
	)
	return i, err
}

const createServerPending = `-- name: CreateServerPending :one
INSERT INTO servers (user_id, hostname, client_token, status, last_seen)
VALUES ($1, $2, $3, 'pending', NOW())
RETURNING id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token
`

type CreateServerPendingParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Hostname    string      `json:"hostname"`
	ClientToken pgtype.Text `json:"client_token"`
}

func (q *Queries) CreateServerPending(ctx context.Context, arg CreateServerPendingParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServerPending, arg.UserID, arg.Hostname, arg.ClientToken)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
	)
	return i, err
}

const createServerWithAPIKey = `-- name: CreateServerWithAPIKey :one
INSERT INTO servers (user_id, hostname, api_key, client_token, ip_address, status, last_seen)
VALUES ($1, $2, $3, $4, $5, 'pending', NOW())
RETURNING id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token
`

type CreateServerWithAPIKeyParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Hostname    string      `json:"hostname"`
	ApiKey      pgtype.Text `json:"api_key"`
	ClientToken pgtype.Text `json:"client_token"`
	IpAddress   *netip.Addr `json:"ip_address"`
}

func (q *Queries) CreateServerWithAPIKey(ctx context.Context, arg CreateServerWithAPIKeyParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServerWithAPIKey,
		arg.UserID,
		arg.Hostname,
		arg.ApiKey,
		arg.ClientToken,
		arg.IpAddress,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, plan)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, plan, max_servers, stripe_customer_id, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Plan         string `json:"plan"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Plan)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Plan,
		&i.MaxServers,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers
WHERE id = $1 AND user_id = $2
`

type DeleteServerParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteServer(ctx context.Context, arg DeleteServerParams) error {
	_, err := q.db.Exec(ctx, deleteServer, arg.ID, arg.UserID)
	return err
}

const getServerByAPIKey = `-- name: GetServerByAPIKey :one
SELECT id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token FROM servers
WHERE api_key = $1
`

func (q *Queries) GetServerByAPIKey(ctx context.Context, apiKey pgtype.Text) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByAPIKey, apiKey)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
	)
	return i, err
}

const getServerByClientToken = `-- name: GetServerByClientToken :one
SELECT id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token FROM servers
WHERE client_token = $1
`

func (q *Queries) GetServerByClientToken(ctx context.Context, clientToken pgtype.Text) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByClientToken, clientToken)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
	)
	return i, err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token FROM servers
WHERE id = $1
`

func (q *Queries) GetServerByID(ctx context.Context, id pgtype.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
	)
	return i, err
}

const getServerByUserAndIP = `-- name: GetServerByUserAndIP :one
SELECT id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token FROM servers
WHERE user_id = $1 AND ip_address = $2
`

type GetServerByUserAndIPParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	IpAddress *netip.Addr `json:"ip_address"`
}

func (q *Queries) GetServerByUserAndIP(ctx context.Context, arg GetServerByUserAndIPParams) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByUserAndIP, arg.UserID, arg.IpAddress)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
	)
	return i, err
}

const getServerStats = `-- name: GetServerStats :one
SELECT 
    COUNT(*)::bigint as total_events,
    COUNT(*) FILTER (WHERE created_at > NOW() - INTERVAL '24 hours')::bigint as events_last_24h,
    COUNT(*) FILTER (WHERE threat_level IN ('suspicious', 'malicious'))::int as threat_events,
    COALESCE(SUM(bytes_in), 0)::bigint as total_bytes_in,
    COALESCE(SUM(bytes_out), 0)::bigint as total_bytes_out
FROM traffic_events
WHERE server_id = $1
`

type GetServerStatsRow struct {
	TotalEvents   int64 `json:"total_events"`
	EventsLast24h int64 `json:"events_last_24h"`
	ThreatEvents  int32 `json:"threat_events"`
	TotalBytesIn  int64 `json:"total_bytes_in"`
	TotalBytesOut int64 `json:"total_bytes_out"`
}

func (q *Queries) GetServerStats(ctx context.Context, serverID pgtype.UUID) (GetServerStatsRow, error) {
	row := q.db.QueryRow(ctx, getServerStats, serverID)
	var i GetServerStatsRow
	err := row.Scan(
		&i.TotalEvents,
		&i.EventsLast24h,
		&i.ThreatEvents,
		&i.TotalBytesIn,
		&i.TotalBytesOut,
	)
	return i, err
}

const getStatsAlertCounts = `-- name: GetStatsAlertCounts :one
SELECT 
    COUNT(*)::int as total_alerts,
    COUNT(*) FILTER (WHERE a.created_at > NOW() - INTERVAL '24 hours')::int as alerts_last_24h,
    COUNT(*) FILTER (WHERE a.status = 'active')::int as active_threats
FROM alerts a
JOIN servers s ON a.server_id = s.id
WHERE s.user_id = $1
`

type GetStatsAlertCountsRow struct {
	TotalAlerts   int32 `json:"total_alerts"`
	AlertsLast24h int32 `json:"alerts_last_24h"`
	ActiveThreats int32 `json:"active_threats"`
}

func (q *Queries) GetStatsAlertCounts(ctx context.Context, userID pgtype.UUID) (GetStatsAlertCountsRow, error) {
	row := q.db.QueryRow(ctx, getStatsAlertCounts, userID)
	var i GetStatsAlertCountsRow
	err := row.Scan(&i.TotalAlerts, &i.AlertsLast24h, &i.ActiveThreats)
	return i, err
}

const getStatsEventCounts = `-- name: GetStatsEventCounts :one
SELECT 
    COUNT(*)::bigint as total_events,
    COUNT(*) FILTER (WHERE te.created_at > NOW() - INTERVAL '24 hours')::bigint as events_last_24h
FROM traffic_events te
JOIN servers s ON te.server_id = s.id
WHERE s.user_id = $1
`

type GetStatsEventCountsRow struct {
	TotalEvents   int64 `json:"total_events"`
	EventsLast24h int64 `json:"events_last_24h"`
}

func (q *Queries) GetStatsEventCounts(ctx context.Context, userID pgtype.UUID) (GetStatsEventCountsRow, error) {
	row := q.db.QueryRow(ctx, getStatsEventCounts, userID)
	var i GetStatsEventCountsRow
	err := row.Scan(&i.TotalEvents, &i.EventsLast24h)
	return i, err
}

const getStatsServerCounts = `-- name: GetStatsServerCounts :one
SELECT 
    COUNT(*)::int as total_servers,
    COUNT(*) FILTER (WHERE status = 'active')::int as active_servers
FROM servers 
WHERE user_id = $1
`

type GetStatsServerCountsRow struct {
	TotalServers  int32 `json:"total_servers"`
	ActiveServers int32 `json:"active_servers"`
}

func (q *Queries) GetStatsServerCounts(ctx context.Context, userID pgtype.UUID) (GetStatsServerCountsRow, error) {
	row := q.db.QueryRow(ctx, getStatsServerCounts, userID)
	var i GetStatsServerCountsRow
	err := row.Scan(&i.TotalServers, &i.ActiveServers)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, plan, max_servers, stripe_customer_id, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Plan,
		&i.MaxServers,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, plan, max_servers, stripe_customer_id, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Plan,
		&i.MaxServers,
		&i.StripeCustomerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAlerts = `-- name: ListAlerts :many
SELECT a.id, a.server_id, a.source_ip, a.threat_score, a.reason, a.severity, a.status, a.auto_blocked, a.blocked_until, a.created_at, a.acknowledged_at, a.resolved_at FROM alerts a
JOIN servers s ON a.server_id = s.id
WHERE s.user_id = $1
ORDER BY a.created_at DESC
LIMIT $2
`

type ListAlertsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlerts, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.SourceIp,
			&i.ThreatScore,
			&i.Reason,
			&i.Severity,
			&i.Status,
			&i.AutoBlocked,
			&i.BlockedUntil,
			&i.CreatedAt,
			&i.AcknowledgedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersByUser = `-- name: ListServersByUser :many
SELECT id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token FROM servers
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListServersByUser(ctx context.Context, userID pgtype.UUID) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Hostname,
			&i.IpAddress,
			&i.ApiKey,
			&i.Status,
			&i.LastSeen,
			&i.AgentVersion,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreats = `-- name: ListThreats :many
SELECT te.id, te.server_id, te.source_ip, te.destination_port, te.protocol, te.syn_count, te.ack_count, te.failed_handshakes, te.unique_ports, te.bytes_in, te.bytes_out, te.threat_score, te.threat_level, te.first_seen, te.last_seen, te.created_at, te.country, te.city, te.isp, te.hit_count, te.direction, te.destination_ip FROM traffic_events te
JOIN servers s ON te.server_id = s.id
WHERE s.user_id = $1 
  AND te.threat_level IN ('suspicious', 'malicious')
ORDER BY te.threat_score DESC, te.created_at DESC
LIMIT $2
`

type ListThreatsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListThreats(ctx context.Context, arg ListThreatsParams) ([]TrafficEvent, error) {
	rows, err := q.db.Query(ctx, listThreats, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficEvent{}
	for rows.Next() {
		var i TrafficEvent
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.SourceIp,
			&i.DestinationPort,
			&i.Protocol,
			&i.SynCount,
			&i.AckCount,
			&i.FailedHandshakes,
			&i.UniquePorts,
			&i.BytesIn,
			&i.BytesOut,
			&i.ThreatScore,
			&i.ThreatLevel,
			&i.FirstSeen,
			&i.LastSeen,
			&i.CreatedAt,
			&i.Country,
			&i.City,
			&i.Isp,
			&i.HitCount,
			&i.Direction,
			&i.DestinationIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrafficEventsByServer = `-- name: ListTrafficEventsByServer :many
SELECT id, server_id, source_ip, destination_port, protocol, syn_count, ack_count, failed_handshakes, unique_ports, bytes_in, bytes_out, threat_score, threat_level, first_seen, last_seen, created_at, country, city, isp, hit_count, direction, destination_ip FROM traffic_events
WHERE server_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListTrafficEventsByServerParams struct {
	ServerID pgtype.UUID `json:"server_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListTrafficEventsByServer(ctx context.Context, arg ListTrafficEventsByServerParams) ([]TrafficEvent, error) {
	rows, err := q.db.Query(ctx, listTrafficEventsByServer, arg.ServerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficEvent{}
	for rows.Next() {
		var i TrafficEvent
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.SourceIp,
			&i.DestinationPort,
			&i.Protocol,
			&i.SynCount,
			&i.AckCount,
			&i.FailedHandshakes,
			&i.UniquePorts,
			&i.BytesIn,
			&i.BytesOut,
			&i.ThreatScore,
			&i.ThreatLevel,
			&i.FirstSeen,
			&i.LastSeen,
			&i.CreatedAt,
			&i.Country,
			&i.City,
			&i.Isp,
			&i.HitCount,
			&i.Direction,
			&i.DestinationIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServerForReenrollment = `-- name: UpdateServerForReenrollment :one
UPDATE servers
SET api_key = $2,
    hostname = $3,
    client_token = $4,
    status = 'active',
    last_seen = NOW()
WHERE id = $1
RETURNING id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token
`

type UpdateServerForReenrollmentParams struct {
	ID          pgtype.UUID `json:"id"`
	ApiKey      pgtype.Text `json:"api_key"`
	Hostname    string      `json:"hostname"`
	ClientToken pgtype.Text `json:"client_token"`
}

func (q *Queries) UpdateServerForReenrollment(ctx context.Context, arg UpdateServerForReenrollmentParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServerForReenrollment,
		arg.ID,
		arg.ApiKey,
		arg.Hostname,
		arg.ClientToken,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
	)
	return i, err
}

const updateServerHeartbeat = `-- name: UpdateServerHeartbeat :exec
UPDATE servers 
SET last_seen = NOW(), 
    agent_version = $1, 
    ip_address = COALESCE(ip_address, $2),
    status = 'active'
WHERE api_key = $3
`

type UpdateServerHeartbeatParams struct {
	AgentVersion pgtype.Text `json:"agent_version"`
	IpAddress    *netip.Addr `json:"ip_address"`
	ApiKey       pgtype.Text `json:"api_key"`
}

func (q *Queries) UpdateServerHeartbeat(ctx context.Context, arg UpdateServerHeartbeatParams) error {
	_, err := q.db.Exec(ctx, updateServerHeartbeat, arg.AgentVersion, arg.IpAddress, arg.ApiKey)
	return err
}

const updateServerStatus = `-- name: UpdateServerStatus :exec
UPDATE servers
SET status = $2
WHERE id = $1
`

type UpdateServerStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateServerStatus(ctx context.Context, arg UpdateServerStatusParams) error {
	_, err := q.db.Exec(ctx, updateServerStatus, arg.ID, arg.Status)
	return err
}

const upsertTrafficEvent = `-- name: UpsertTrafficEvent :one
INSERT INTO traffic_events (
    server_id, source_ip, destination_ip, destination_port, protocol, direction,
    syn_count, ack_count, failed_handshakes, unique_ports,
    bytes_in, bytes_out, threat_score, threat_level,
    first_seen, last_seen, country, city, isp, hit_count
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, 1)
ON CONFLICT (server_id, source_ip, destination_ip, destination_port, direction) DO UPDATE SET
    syn_count = traffic_events.syn_count + EXCLUDED.syn_count,
    ack_count = traffic_events.ack_count + EXCLUDED.ack_count,
    failed_handshakes = traffic_events.failed_handshakes + EXCLUDED.failed_handshakes,
    unique_ports = GREATEST(traffic_events.unique_ports, EXCLUDED.unique_ports),
    bytes_in = traffic_events.bytes_in + EXCLUDED.bytes_in,
    bytes_out = traffic_events.bytes_out + EXCLUDED.bytes_out,
    threat_score = GREATEST(traffic_events.threat_score, EXCLUDED.threat_score),
    threat_level = CASE 
        WHEN EXCLUDED.threat_score > traffic_events.threat_score THEN EXCLUDED.threat_level 
        ELSE traffic_events.threat_level 
    END,
    last_seen = EXCLUDED.last_seen,
    hit_count = traffic_events.hit_count + 1
RETURNING id, server_id, source_ip, destination_port, protocol, syn_count, ack_count, failed_handshakes, unique_ports, bytes_in, bytes_out, threat_score, threat_level, first_seen, last_seen, created_at, country, city, isp, hit_count, direction, destination_ip
`

type UpsertTrafficEventParams struct {
	ServerID         pgtype.UUID        `json:"server_id"`
	SourceIp         netip.Addr         `json:"source_ip"`
	DestinationIp    *netip.Addr        `json:"destination_ip"`
	DestinationPort  int32              `json:"destination_port"`
	Protocol         string             `json:"protocol"`
	Direction        string             `json:"direction"`
	SynCount         int32              `json:"syn_count"`
	AckCount         int32              `json:"ack_count"`
	FailedHandshakes int32              `json:"failed_handshakes"`
	UniquePorts      int32              `json:"unique_ports"`
	BytesIn          int64              `json:"bytes_in"`
	BytesOut         int64              `json:"bytes_out"`
	ThreatScore      int32              `json:"threat_score"`
	ThreatLevel      string             `json:"threat_level"`
	FirstSeen        pgtype.Timestamptz `json:"first_seen"`
	LastSeen         pgtype.Timestamptz `json:"last_seen"`
	Country          pgtype.Text        `json:"country"`
	City             pgtype.Text        `json:"city"`
	Isp              pgtype.Text        `json:"isp"`
}

func (q *Queries) UpsertTrafficEvent(ctx context.Context, arg UpsertTrafficEventParams) (TrafficEvent, error) {
	row := q.db.QueryRow(ctx, upsertTrafficEvent,
		arg.ServerID,
		arg.SourceIp,
		arg.DestinationIp,
		arg.DestinationPort,
		arg.Protocol,
		arg.Direction,
		arg.SynCount,
		arg.AckCount,
		arg.FailedHandshakes,
		arg.UniquePorts,
		arg.BytesIn,
		arg.BytesOut,
		arg.ThreatScore,
		arg.ThreatLevel,
		arg.FirstSeen,
		arg.LastSeen,
		arg.Country,
		arg.City,
		arg.Isp,
	)
	var i TrafficEvent
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.SourceIp,
		&i.DestinationPort,
		&i.Protocol,
		&i.SynCount,
		&i.AckCount,
		&i.FailedHandshakes,
		&i.UniquePorts,
		&i.BytesIn,
		&i.BytesOut,
		&i.ThreatScore,
		&i.ThreatLevel,
		&i.FirstSeen,
		&i.LastSeen,
		&i.CreatedAt,
		&i.Country,
		&i.City,
		&i.Isp,
		&i.HitCount,
		&i.Direction,
		&i.DestinationIp,
	)
	return i, err
}
