// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================
	// Whitelist Queries
	// ============================================
	AddToWhitelist(ctx context.Context, arg AddToWhitelistParams) (Whitelist, error)
	// ============================================
	// Data Retention Queries
	// ============================================
	// Archives old traffic events based on retention policy
	ArchiveTrafficEvents(ctx context.Context, arg ArchiveTrafficEventsParams) (int32, error)
	CleanupExpiredBlocks(ctx context.Context) error
	// Deletes archived data older than 1 year
	CleanupOldArchives(ctx context.Context) (int32, error)
	ClearUserRefreshToken(ctx context.Context, id pgtype.UUID) (User, error)
	CountActiveBlocks(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountBlocks(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountBlocksToday(ctx context.Context, userID pgtype.UUID) (int64, error)
	// Returns count of source IPs for a specific port/protocol combination
	CountPortSourcesByServer(ctx context.Context, arg CountPortSourcesByServerParams) (int32, error)
	// Returns count of unique port/protocol/service combinations
	CountPortTrafficByServer(ctx context.Context, arg CountPortTrafficByServerParams) (int32, error)
	// Returns count of unique protocols
	CountProtocolTrafficByServer(ctx context.Context, arg CountProtocolTrafficByServerParams) (int32, error)
	CountServersByUser(ctx context.Context, userID pgtype.UUID) (int32, error)
	CountTrafficEventsByServer(ctx context.Context, arg CountTrafficEventsByServerParams) (int32, error)
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	// Blocks queries for the dashboard and API
	CreateBlock(ctx context.Context, arg CreateBlockParams) (Block, error)
	CreateServer(ctx context.Context, arg CreateServerParams) (Server, error)
	CreateServerPending(ctx context.Context, arg CreateServerPendingParams) (Server, error)
	CreateServerWithAPIKey(ctx context.Context, arg CreateServerWithAPIKeyParams) (Server, error)
	CreateSubscriptionEvent(ctx context.Context, arg CreateSubscriptionEventParams) (SubscriptionEvent, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteServer(ctx context.Context, id pgtype.UUID) error
	GetActiveBlockByIP(ctx context.Context, arg GetActiveBlockByIPParams) (Block, error)
	// Gets active blocks for a specific server (for state reconciliation)
	GetActiveBlocksForServer(ctx context.Context, serverID pgtype.UUID) ([]GetActiveBlocksForServerRow, error)
	// Gets all active blocks across all servers (for BlockManager state recovery).
	// Includes permanent blocks (expires_at IS NULL) which have no expiry.
	GetAllActiveBlocks(ctx context.Context) ([]GetAllActiveBlocksRow, error)
	// Gets all servers with their data retention settings for archival job
	GetAllServersWithRetention(ctx context.Context) ([]GetAllServersWithRetentionRow, error)
	// Returns count of archived events for a server
	GetArchivedEventsCount(ctx context.Context, serverID pgtype.UUID) (int64, error)
	GetAttackTypeBreakdown(ctx context.Context, arg GetAttackTypeBreakdownParams) ([]GetAttackTypeBreakdownRow, error)
	GetBlockByID(ctx context.Context, arg GetBlockByIDParams) (GetBlockByIDRow, error)
	GetBlockRemainingTime(ctx context.Context, arg GetBlockRemainingTimeParams) (int64, error)
	GetBlockStatsByCountry(ctx context.Context, userID pgtype.UUID) ([]GetBlockStatsByCountryRow, error)
	GetBlockStatsByServer(ctx context.Context, userID pgtype.UUID) ([]GetBlockStatsByServerRow, error)
	// Statistics queries
	GetBlockStatsByService(ctx context.Context, userID pgtype.UUID) ([]GetBlockStatsByServiceRow, error)
	GetBlockStatsByThreatLevel(ctx context.Context, userID pgtype.UUID) ([]GetBlockStatsByThreatLevelRow, error)
	// Gets IPs that exceed the scoring threshold for potential blocking
	// Uses MAX for geo fields to avoid grouping issues and get most recent values
	GetBlockableIPs(ctx context.Context, arg GetBlockableIPsParams) ([]GetBlockableIPsRow, error)
	// ============================================
	// Reports & Analytics Queries
	// ============================================
	GetDailyAttackStats(ctx context.Context, arg GetDailyAttackStatsParams) ([]GetDailyAttackStatsRow, error)
	// Get blocked IPs stats from blocks table (actually prevented attacks)
	GetDailyBlockStats(ctx context.Context, arg GetDailyBlockStatsParams) ([]GetDailyBlockStatsRow, error)
	// Gets IPs with scores above threshold for potential blocking
	GetHighScoreTraffic(ctx context.Context, arg GetHighScoreTrafficParams) ([]GetHighScoreTrafficRow, error)
	// Uses actual blocks from blocks table for accurate blocked_count
	// rather than estimating from traffic_events threat_level
	GetHourlyAttackDistribution(ctx context.Context, arg GetHourlyAttackDistributionParams) ([]GetHourlyAttackDistributionRow, error)
	// Returns aggregate prior enforcement counts for a given IP+user across all
	// time (including expired/unblocked records). Used by the escalation engine.
	GetIPEnforcementHistory(ctx context.Context, arg GetIPEnforcementHistoryParams) (GetIPEnforcementHistoryRow, error)
	// Gets historical traffic for a specific IP across all servers
	GetIPTrafficHistory(ctx context.Context, arg GetIPTrafficHistoryParams) ([]GetIPTrafficHistoryRow, error)
	// Returns the most recent block record for a given IP and user regardless of
	// active status – used as a context fallback during startup sync.
	GetLatestBlockByIP(ctx context.Context, arg GetLatestBlockByIPParams) (Block, error)
	// Gets total blocked connection count for a user in a date range
	GetMonthlyBlockStats(ctx context.Context, arg GetMonthlyBlockStatsParams) (int64, error)
	// Gets count of threat-level traffic events (non-normal)
	GetMonthlyThreatStats(ctx context.Context, arg GetMonthlyThreatStatsParams) (int64, error)
	// Gets top blocked IPs for a user in a date range (top 5)
	GetMonthlyTopBlockedIPs(ctx context.Context, arg GetMonthlyTopBlockedIPsParams) ([]GetMonthlyTopBlockedIPsRow, error)
	// Gets top attacking countries for a user in a date range (top 5)
	GetMonthlyTopCountries(ctx context.Context, arg GetMonthlyTopCountriesParams) ([]GetMonthlyTopCountriesRow, error)
	// Gets top targeted ports for a user in a date range (top 5)
	GetMonthlyTopPorts(ctx context.Context, arg GetMonthlyTopPortsParams) ([]GetMonthlyTopPortsRow, error)
	// Gets total traffic event count for a user in a date range
	GetMonthlyTrafficStats(ctx context.Context, arg GetMonthlyTrafficStatsParams) (int64, error)
	// Gets count of unique threat IPs for a user in a date range
	GetMonthlyUniqueThreatIPs(ctx context.Context, arg GetMonthlyUniqueThreatIPsParams) (int64, error)
	GetPlanByName(ctx context.Context, name string) (SubscriptionPlan, error)
	GetPlanByPolarProductID(ctx context.Context, polarProductID pgtype.Text) (SubscriptionPlan, error)
	GetRecentBlocks(ctx context.Context, arg GetRecentBlocksParams) ([]GetRecentBlocksRow, error)
	// Gets IPs that have been active within the time window
	GetRecentlyActiveIPs(ctx context.Context, arg GetRecentlyActiveIPsParams) ([]GetRecentlyActiveIPsRow, error)
	GetServerByAPIKey(ctx context.Context, apiKey pgtype.Text) (Server, error)
	GetServerByClientToken(ctx context.Context, clientToken pgtype.Text) (Server, error)
	GetServerByID(ctx context.Context, id pgtype.UUID) (Server, error)
	GetServerByUserAndIP(ctx context.Context, arg GetServerByUserAndIPParams) (Server, error)
	// Gets the data retention days for a server's user
	GetServerDataRetentionDays(ctx context.Context, id pgtype.UUID) (int32, error)
	GetServerStats(ctx context.Context, serverID pgtype.UUID) (GetServerStatsRow, error)
	GetSourceIPTimeline(ctx context.Context, arg GetSourceIPTimelineParams) ([]GetSourceIPTimelineRow, error)
	GetStatsAlertCounts(ctx context.Context, userID pgtype.UUID) (GetStatsAlertCountsRow, error)
	GetStatsEventCounts(ctx context.Context, userID pgtype.UUID) (GetStatsEventCountsRow, error)
	GetStatsServerCounts(ctx context.Context, userID pgtype.UUID) (GetStatsServerCountsRow, error)
	GetThreatTrends(ctx context.Context, arg GetThreatTrendsParams) ([]GetThreatTrendsRow, error)
	GetTopASNs(ctx context.Context, arg GetTopASNsParams) ([]GetTopASNsRow, error)
	GetTopSourceCountries(ctx context.Context, arg GetTopSourceCountriesParams) ([]GetTopSourceCountriesRow, error)
	GetTopSourceIPs(ctx context.Context, arg GetTopSourceIPsParams) ([]GetTopSourceIPsRow, error)
	// ============================================
	// Traffic Aggregation Queries for Backend Scoring
	// ============================================
	// Aggregates traffic by source_ip over a given time window for scoring
	GetTrafficAggregationByIP(ctx context.Context, arg GetTrafficAggregationByIPParams) ([]GetTrafficAggregationByIPRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// ============================================
	// User Polar Integration Queries
	// ============================================
	GetUserByPolarCustomerID(ctx context.Context, polarCustomerID pgtype.Text) (User, error)
	GetUserByRefreshToken(ctx context.Context, refreshToken pgtype.Text) (User, error)
	// Gets high score traffic for all servers owned by user
	GetUserHighScoreTraffic(ctx context.Context, arg GetUserHighScoreTrafficParams) ([]GetUserHighScoreTrafficRow, error)
	GetUserSubscriptionStatus(ctx context.Context, id pgtype.UUID) (GetUserSubscriptionStatusRow, error)
	GetWhitelistByUser(ctx context.Context, userID pgtype.UUID) ([]Whitelist, error)
	GetWhitelistedIPs(ctx context.Context, userID pgtype.UUID) ([]netip.Addr, error)
	// Check if an IP has attacked any of the user's servers
	IsIPAttackingUserServer(ctx context.Context, arg IsIPAttackingUserServerParams) (bool, error)
	IsIPBlocked(ctx context.Context, arg IsIPBlockedParams) (bool, error)
	IsIPWhitelisted(ctx context.Context, arg IsIPWhitelistedParams) (bool, error)
	ListActivePlans(ctx context.Context) ([]SubscriptionPlan, error)
	ListAlerts(ctx context.Context, arg ListAlertsParams) ([]ListAlertsRow, error)
	ListAllActiveServers(ctx context.Context) ([]ListAllActiveServersRow, error)
	ListBlocks(ctx context.Context, arg ListBlocksParams) ([]ListBlocksRow, error)
	// Returns paginated source IPs for a specific port/protocol combination
	ListPortSourcesByServer(ctx context.Context, arg ListPortSourcesByServerParams) ([]ListPortSourcesByServerRow, error)
	// Returns aggregated traffic data grouped by port and protocol with source IPs as JSON array
	ListPortTrafficByServer(ctx context.Context, arg ListPortTrafficByServerParams) ([]ListPortTrafficByServerRow, error)
	// Returns aggregated traffic data grouped by protocol with all source IPs
	ListProtocolTrafficByServer(ctx context.Context, arg ListProtocolTrafficByServerParams) ([]ListProtocolTrafficByServerRow, error)
	ListServersByUser(ctx context.Context, userID pgtype.UUID) ([]Server, error)
	ListThreats(ctx context.Context, arg ListThreatsParams) ([]TrafficEvent, error)
	ListTrafficEventsByServer(ctx context.Context, arg ListTrafficEventsByServerParams) ([]TrafficEvent, error)
	// ============================================
	// Monthly Report Queries
	// ============================================
	// Gets all users with email addresses for monthly reports
	ListUsersForReports(ctx context.Context) ([]ListUsersForReportsRow, error)
	RemoveFromWhitelist(ctx context.Context, arg RemoveFromWhitelistParams) error
	// Reset threat score for an IP after unblock (keeps history for future calculations)
	// Sets score to 0 and level to normal, but preserves traffic counts
	ResetTrafficScoreForIP(ctx context.Context, arg ResetTrafficScoreForIPParams) error
	UnblockIP(ctx context.Context, arg UnblockIPParams) error
	// Backfill target_port / service_name / protocol on an existing block that was
	// created without context (e.g. startup-sync from XDP/ipset).
	// Only overwrites columns that are still NULL so we never clobber real data.
	UpdateBlockContext(ctx context.Context, arg UpdateBlockContextParams) error
	UpdateBlockExpiry(ctx context.Context, arg UpdateBlockExpiryParams) error
	UpdateServerAPIKey(ctx context.Context, arg UpdateServerAPIKeyParams) error
	UpdateServerConfig(ctx context.Context, arg UpdateServerConfigParams) error
	UpdateServerForReenrollment(ctx context.Context, arg UpdateServerForReenrollmentParams) (Server, error)
	UpdateServerHeartbeat(ctx context.Context, arg UpdateServerHeartbeatParams) error
	UpdateServerMetadata(ctx context.Context, arg UpdateServerMetadataParams) error
	UpdateServerStatus(ctx context.Context, arg UpdateServerStatusParams) error
	UpdateTrafficScore(ctx context.Context, arg UpdateTrafficScoreParams) error
	UpdateUserPolarCustomerID(ctx context.Context, arg UpdateUserPolarCustomerIDParams) error
	UpdateUserRefreshToken(ctx context.Context, arg UpdateUserRefreshTokenParams) (User, error)
	UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error
	UpdateUserTrial(ctx context.Context, arg UpdateUserTrialParams) error
	UpsertTrafficEvent(ctx context.Context, arg UpsertTrafficEventParams) (TrafficEvent, error)
}

var _ Querier = (*Queries)(nil)
