// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearUserRefreshToken = `-- name: ClearUserRefreshToken :one
UPDATE users
SET refresh_token = NULL,
    refresh_token_expires_at = NULL
WHERE id = $1
RETURNING id, email, password_hash, plan, max_servers, created_at, updated_at, polar_customer_id, polar_subscription_id, subscription_status, subscription_current_period_start, subscription_current_period_end, subscription_cancel_at_period_end, trial_ends_at, has_used_trial, refresh_token, refresh_token_expires_at
`

func (q *Queries) ClearUserRefreshToken(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, clearUserRefreshToken, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Plan,
		&i.MaxServers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PolarCustomerID,
		&i.PolarSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionCurrentPeriodStart,
		&i.SubscriptionCurrentPeriodEnd,
		&i.SubscriptionCancelAtPeriodEnd,
		&i.TrialEndsAt,
		&i.HasUsedTrial,
		&i.RefreshToken,
		&i.RefreshTokenExpiresAt,
	)
	return i, err
}

const countServersByUser = `-- name: CountServersByUser :one
SELECT COUNT(*)::int FROM servers
WHERE user_id = $1
`

func (q *Queries) CountServersByUser(ctx context.Context, userID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countServersByUser, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createAlert = `-- name: CreateAlert :one
INSERT INTO alerts (server_id, source_ip, threat_score, reason, severity, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, server_id, source_ip, threat_score, reason, severity, status, auto_blocked, blocked_until, created_at, acknowledged_at, resolved_at
`

type CreateAlertParams struct {
	ServerID    pgtype.UUID `json:"server_id"`
	SourceIp    netip.Addr  `json:"source_ip"`
	ThreatScore int32       `json:"threat_score"`
	Reason      string      `json:"reason"`
	Severity    string      `json:"severity"`
	Status      string      `json:"status"`
}

func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.ServerID,
		arg.SourceIp,
		arg.ThreatScore,
		arg.Reason,
		arg.Severity,
		arg.Status,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.SourceIp,
		&i.ThreatScore,
		&i.Reason,
		&i.Severity,
		&i.Status,
		&i.AutoBlocked,
		&i.BlockedUntil,
		&i.CreatedAt,
		&i.AcknowledgedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const createServer = `-- name: CreateServer :one
INSERT INTO servers (user_id, hostname, api_key, last_seen)
VALUES ($1, $2, $3, NOW())
RETURNING id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token, config
`

type CreateServerParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Hostname string      `json:"hostname"`
	ApiKey   pgtype.Text `json:"api_key"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer, arg.UserID, arg.Hostname, arg.ApiKey)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
		&i.Config,
	)
	return i, err
}

const createServerPending = `-- name: CreateServerPending :one
INSERT INTO servers (user_id, hostname, client_token, status, last_seen)
VALUES ($1, $2, $3, 'pending', NOW())
RETURNING id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token, config
`

type CreateServerPendingParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Hostname    string      `json:"hostname"`
	ClientToken pgtype.Text `json:"client_token"`
}

func (q *Queries) CreateServerPending(ctx context.Context, arg CreateServerPendingParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServerPending, arg.UserID, arg.Hostname, arg.ClientToken)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
		&i.Config,
	)
	return i, err
}

const createServerWithAPIKey = `-- name: CreateServerWithAPIKey :one
INSERT INTO servers (user_id, hostname, api_key, client_token, ip_address, status, last_seen)
VALUES ($1, $2, $3, $4, $5, 'pending', NOW())
RETURNING id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token, config
`

type CreateServerWithAPIKeyParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Hostname    string      `json:"hostname"`
	ApiKey      pgtype.Text `json:"api_key"`
	ClientToken pgtype.Text `json:"client_token"`
	IpAddress   *netip.Addr `json:"ip_address"`
}

func (q *Queries) CreateServerWithAPIKey(ctx context.Context, arg CreateServerWithAPIKeyParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServerWithAPIKey,
		arg.UserID,
		arg.Hostname,
		arg.ApiKey,
		arg.ClientToken,
		arg.IpAddress,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
		&i.Config,
	)
	return i, err
}

const createSubscriptionEvent = `-- name: CreateSubscriptionEvent :one
INSERT INTO subscription_events (
    user_id, polar_event_id, event_type, payload, processed_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, polar_event_id, event_type, payload, processed, processed_at, error_message, created_at
`

type CreateSubscriptionEventParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	PolarEventID pgtype.Text        `json:"polar_event_id"`
	EventType    string             `json:"event_type"`
	Payload      []byte             `json:"payload"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
}

func (q *Queries) CreateSubscriptionEvent(ctx context.Context, arg CreateSubscriptionEventParams) (SubscriptionEvent, error) {
	row := q.db.QueryRow(ctx, createSubscriptionEvent,
		arg.UserID,
		arg.PolarEventID,
		arg.EventType,
		arg.Payload,
		arg.ProcessedAt,
	)
	var i SubscriptionEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PolarEventID,
		&i.EventType,
		&i.Payload,
		&i.Processed,
		&i.ProcessedAt,
		&i.ErrorMessage,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, plan)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, plan, max_servers, created_at, updated_at, polar_customer_id, polar_subscription_id, subscription_status, subscription_current_period_start, subscription_current_period_end, subscription_cancel_at_period_end, trial_ends_at, has_used_trial, refresh_token, refresh_token_expires_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Plan         string `json:"plan"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.Plan)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Plan,
		&i.MaxServers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PolarCustomerID,
		&i.PolarSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionCurrentPeriodStart,
		&i.SubscriptionCurrentPeriodEnd,
		&i.SubscriptionCancelAtPeriodEnd,
		&i.TrialEndsAt,
		&i.HasUsedTrial,
		&i.RefreshToken,
		&i.RefreshTokenExpiresAt,
	)
	return i, err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers
WHERE id = $1
`

func (q *Queries) DeleteServer(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteServer, id)
	return err
}

const getAttackTypeBreakdown = `-- name: GetAttackTypeBreakdown :many
SELECT 
    CASE 
        WHEN te.destination_port = 22 THEN 'SSH Bruteforce'
        WHEN te.destination_port = 80 THEN 'HTTP Attack'
        WHEN te.destination_port = 443 THEN 'HTTPS Attack'
        WHEN te.destination_port IN (21, 23, 25, 3306, 5432, 6379, 27017) THEN 'Service Attack'
        ELSE 'Port Scan'
    END as attack_type,
    SUM(te.hit_count)::int as count,
    COUNT(DISTINCT te.source_ip)::int as unique_sources
FROM traffic_events te
JOIN servers s ON te.server_id = s.id
WHERE s.user_id = $1
  AND te.created_at >= $2
  AND te.created_at <= $3
GROUP BY 
    CASE 
        WHEN te.destination_port = 22 THEN 'SSH Bruteforce'
        WHEN te.destination_port = 80 THEN 'HTTP Attack'
        WHEN te.destination_port = 443 THEN 'HTTPS Attack'
        WHEN te.destination_port IN (21, 23, 25, 3306, 5432, 6379, 27017) THEN 'Service Attack'
        ELSE 'Port Scan'
    END
ORDER BY count DESC
`

type GetAttackTypeBreakdownParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetAttackTypeBreakdownRow struct {
	AttackType    string `json:"attack_type"`
	Count         int32  `json:"count"`
	UniqueSources int32  `json:"unique_sources"`
}

func (q *Queries) GetAttackTypeBreakdown(ctx context.Context, arg GetAttackTypeBreakdownParams) ([]GetAttackTypeBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getAttackTypeBreakdown, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttackTypeBreakdownRow{}
	for rows.Next() {
		var i GetAttackTypeBreakdownRow
		if err := rows.Scan(&i.AttackType, &i.Count, &i.UniqueSources); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDailyAttackStats = `-- name: GetDailyAttackStats :many

SELECT 
    DATE(te.created_at) as date,
    COUNT(*)::int as total_attacks,
    SUM(te.hit_count)::int as total_events,
    COUNT(DISTINCT te.source_ip)::int as unique_sources,
    SUM(CASE WHEN te.threat_level = 'malicious' THEN te.hit_count ELSE 0 END)::int as blocked,
    SUM(CASE WHEN te.destination_port = 22 THEN te.hit_count ELSE 0 END)::int as ssh_attacks,
    SUM(CASE WHEN te.destination_port IN (80, 443) THEN te.hit_count ELSE 0 END)::int as http_attacks,
    SUM(CASE WHEN te.destination_port NOT IN (22, 80, 443) THEN te.hit_count ELSE 0 END)::int as other_attacks
FROM traffic_events te
JOIN servers s ON te.server_id = s.id
WHERE s.user_id = $1
  AND te.created_at >= $2
  AND te.created_at <= $3
GROUP BY DATE(te.created_at)
ORDER BY date DESC
`

type GetDailyAttackStatsParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetDailyAttackStatsRow struct {
	Date          pgtype.Date `json:"date"`
	TotalAttacks  int32       `json:"total_attacks"`
	TotalEvents   int32       `json:"total_events"`
	UniqueSources int32       `json:"unique_sources"`
	Blocked       int32       `json:"blocked"`
	SshAttacks    int32       `json:"ssh_attacks"`
	HttpAttacks   int32       `json:"http_attacks"`
	OtherAttacks  int32       `json:"other_attacks"`
}

// ============================================
// Reports & Analytics Queries
// ============================================
func (q *Queries) GetDailyAttackStats(ctx context.Context, arg GetDailyAttackStatsParams) ([]GetDailyAttackStatsRow, error) {
	rows, err := q.db.Query(ctx, getDailyAttackStats, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDailyAttackStatsRow{}
	for rows.Next() {
		var i GetDailyAttackStatsRow
		if err := rows.Scan(
			&i.Date,
			&i.TotalAttacks,
			&i.TotalEvents,
			&i.UniqueSources,
			&i.Blocked,
			&i.SshAttacks,
			&i.HttpAttacks,
			&i.OtherAttacks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHourlyAttackDistribution = `-- name: GetHourlyAttackDistribution :many
SELECT 
    EXTRACT(HOUR FROM te.created_at)::int as hour,
    SUM(te.hit_count)::int as attack_count,
    SUM(CASE WHEN te.threat_level = 'malicious' THEN te.hit_count ELSE 0 END)::int as blocked_count
FROM traffic_events te
JOIN servers s ON te.server_id = s.id
WHERE s.user_id = $1
  AND te.created_at >= $2
  AND te.created_at <= $3
GROUP BY EXTRACT(HOUR FROM te.created_at)
ORDER BY hour
`

type GetHourlyAttackDistributionParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetHourlyAttackDistributionRow struct {
	Hour         int32 `json:"hour"`
	AttackCount  int32 `json:"attack_count"`
	BlockedCount int32 `json:"blocked_count"`
}

func (q *Queries) GetHourlyAttackDistribution(ctx context.Context, arg GetHourlyAttackDistributionParams) ([]GetHourlyAttackDistributionRow, error) {
	rows, err := q.db.Query(ctx, getHourlyAttackDistribution, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHourlyAttackDistributionRow{}
	for rows.Next() {
		var i GetHourlyAttackDistributionRow
		if err := rows.Scan(&i.Hour, &i.AttackCount, &i.BlockedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanByName = `-- name: GetPlanByName :one
SELECT id, name, display_name, description, price_cents, currency, billing_interval, max_servers, data_retention_days, features, polar_product_id, polar_price_id, is_active, is_default, created_at, updated_at FROM subscription_plans
WHERE name = $1
`

func (q *Queries) GetPlanByName(ctx context.Context, name string) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getPlanByName, name)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.BillingInterval,
		&i.MaxServers,
		&i.DataRetentionDays,
		&i.Features,
		&i.PolarProductID,
		&i.PolarPriceID,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanByPolarProductID = `-- name: GetPlanByPolarProductID :one
SELECT id, name, display_name, description, price_cents, currency, billing_interval, max_servers, data_retention_days, features, polar_product_id, polar_price_id, is_active, is_default, created_at, updated_at FROM subscription_plans
WHERE polar_product_id = $1
`

func (q *Queries) GetPlanByPolarProductID(ctx context.Context, polarProductID pgtype.Text) (SubscriptionPlan, error) {
	row := q.db.QueryRow(ctx, getPlanByPolarProductID, polarProductID)
	var i SubscriptionPlan
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DisplayName,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.BillingInterval,
		&i.MaxServers,
		&i.DataRetentionDays,
		&i.Features,
		&i.PolarProductID,
		&i.PolarPriceID,
		&i.IsActive,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServerByAPIKey = `-- name: GetServerByAPIKey :one
SELECT id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token, config FROM servers
WHERE api_key = $1
`

func (q *Queries) GetServerByAPIKey(ctx context.Context, apiKey pgtype.Text) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByAPIKey, apiKey)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
		&i.Config,
	)
	return i, err
}

const getServerByClientToken = `-- name: GetServerByClientToken :one
SELECT id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token, config FROM servers
WHERE client_token = $1
`

func (q *Queries) GetServerByClientToken(ctx context.Context, clientToken pgtype.Text) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByClientToken, clientToken)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
		&i.Config,
	)
	return i, err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token, config FROM servers
WHERE id = $1
`

func (q *Queries) GetServerByID(ctx context.Context, id pgtype.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
		&i.Config,
	)
	return i, err
}

const getServerByUserAndIP = `-- name: GetServerByUserAndIP :one
SELECT id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token, config FROM servers
WHERE user_id = $1 AND ip_address = $2
`

type GetServerByUserAndIPParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	IpAddress *netip.Addr `json:"ip_address"`
}

func (q *Queries) GetServerByUserAndIP(ctx context.Context, arg GetServerByUserAndIPParams) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByUserAndIP, arg.UserID, arg.IpAddress)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
		&i.Config,
	)
	return i, err
}

const getServerStats = `-- name: GetServerStats :one
SELECT 
    COALESCE(SUM(hit_count), 0)::bigint as total_events,
    COUNT(*) FILTER (WHERE created_at >= NOW() - INTERVAL '24 hours')::int as events_last_24h,
    COUNT(*) FILTER (WHERE threat_level = 'malicious')::int as threat_events,
    COALESCE(SUM(bytes_in), 0)::bigint as total_bytes_in,
    COALESCE(SUM(bytes_out), 0)::bigint as total_bytes_out
FROM traffic_events
WHERE server_id = $1
`

type GetServerStatsRow struct {
	TotalEvents   int64 `json:"total_events"`
	EventsLast24h int32 `json:"events_last_24h"`
	ThreatEvents  int32 `json:"threat_events"`
	TotalBytesIn  int64 `json:"total_bytes_in"`
	TotalBytesOut int64 `json:"total_bytes_out"`
}

func (q *Queries) GetServerStats(ctx context.Context, serverID pgtype.UUID) (GetServerStatsRow, error) {
	row := q.db.QueryRow(ctx, getServerStats, serverID)
	var i GetServerStatsRow
	err := row.Scan(
		&i.TotalEvents,
		&i.EventsLast24h,
		&i.ThreatEvents,
		&i.TotalBytesIn,
		&i.TotalBytesOut,
	)
	return i, err
}

const getSourceIPTimeline = `-- name: GetSourceIPTimeline :many
SELECT 
    te.source_ip::text as ip,
    DATE_TRUNC('hour', te.created_at)::timestamp as time_bucket,
    SUM(te.hit_count)::int as count
FROM traffic_events te
JOIN servers s ON te.server_id = s.id
WHERE s.user_id = $1
  AND te.source_ip = $2::inet
  AND te.created_at >= NOW() - INTERVAL '24 hours'
GROUP BY te.source_ip, DATE_TRUNC('hour', te.created_at)
ORDER BY time_bucket
`

type GetSourceIPTimelineParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 netip.Addr  `json:"column_2"`
}

type GetSourceIPTimelineRow struct {
	Ip         string           `json:"ip"`
	TimeBucket pgtype.Timestamp `json:"time_bucket"`
	Count      int32            `json:"count"`
}

func (q *Queries) GetSourceIPTimeline(ctx context.Context, arg GetSourceIPTimelineParams) ([]GetSourceIPTimelineRow, error) {
	rows, err := q.db.Query(ctx, getSourceIPTimeline, arg.UserID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetSourceIPTimelineRow{}
	for rows.Next() {
		var i GetSourceIPTimelineRow
		if err := rows.Scan(&i.Ip, &i.TimeBucket, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatsAlertCounts = `-- name: GetStatsAlertCounts :one
SELECT 
    COUNT(*)::int as total_alerts,
    COUNT(*) FILTER (WHERE severity = 'critical')::int as critical_alerts,
    COUNT(*) FILTER (WHERE severity = 'warning')::int as warning_alerts
FROM alerts a
JOIN servers s ON a.server_id = s.id
WHERE s.user_id = $1
  AND a.created_at >= NOW() - INTERVAL '24 hours'
`

type GetStatsAlertCountsRow struct {
	TotalAlerts    int32 `json:"total_alerts"`
	CriticalAlerts int32 `json:"critical_alerts"`
	WarningAlerts  int32 `json:"warning_alerts"`
}

func (q *Queries) GetStatsAlertCounts(ctx context.Context, userID pgtype.UUID) (GetStatsAlertCountsRow, error) {
	row := q.db.QueryRow(ctx, getStatsAlertCounts, userID)
	var i GetStatsAlertCountsRow
	err := row.Scan(&i.TotalAlerts, &i.CriticalAlerts, &i.WarningAlerts)
	return i, err
}

const getStatsEventCounts = `-- name: GetStatsEventCounts :one
SELECT 
    COALESCE(SUM(hit_count), 0)::bigint as total_events,
    COUNT(DISTINCT te.source_ip)::int as unique_sources
FROM traffic_events te
JOIN servers s ON te.server_id = s.id
WHERE s.user_id = $1
  AND te.created_at >= NOW() - INTERVAL '24 hours'
`

type GetStatsEventCountsRow struct {
	TotalEvents   int64 `json:"total_events"`
	UniqueSources int32 `json:"unique_sources"`
}

func (q *Queries) GetStatsEventCounts(ctx context.Context, userID pgtype.UUID) (GetStatsEventCountsRow, error) {
	row := q.db.QueryRow(ctx, getStatsEventCounts, userID)
	var i GetStatsEventCountsRow
	err := row.Scan(&i.TotalEvents, &i.UniqueSources)
	return i, err
}

const getStatsServerCounts = `-- name: GetStatsServerCounts :one
SELECT 
    COUNT(*)::int as total_servers,
    COUNT(*) FILTER (WHERE status = 'active')::int as active_servers,
    COUNT(*) FILTER (WHERE status = 'inactive')::int as inactive_servers
FROM servers
WHERE user_id = $1
`

type GetStatsServerCountsRow struct {
	TotalServers    int32 `json:"total_servers"`
	ActiveServers   int32 `json:"active_servers"`
	InactiveServers int32 `json:"inactive_servers"`
}

func (q *Queries) GetStatsServerCounts(ctx context.Context, userID pgtype.UUID) (GetStatsServerCountsRow, error) {
	row := q.db.QueryRow(ctx, getStatsServerCounts, userID)
	var i GetStatsServerCountsRow
	err := row.Scan(&i.TotalServers, &i.ActiveServers, &i.InactiveServers)
	return i, err
}

const getThreatTrends = `-- name: GetThreatTrends :many
SELECT 
    DATE_TRUNC('day', te.created_at)::date as date,
    SUM(CASE WHEN te.threat_level = 'normal' THEN te.hit_count ELSE 0 END)::int as normal,
    SUM(CASE WHEN te.threat_level = 'suspicious' THEN te.hit_count ELSE 0 END)::int as suspicious,
    SUM(CASE WHEN te.threat_level = 'malicious' THEN te.hit_count ELSE 0 END)::int as malicious
FROM traffic_events te
JOIN servers s ON te.server_id = s.id
WHERE s.user_id = $1
  AND te.created_at >= $2
  AND te.created_at <= $3
GROUP BY DATE_TRUNC('day', te.created_at)
ORDER BY date DESC
`

type GetThreatTrendsParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetThreatTrendsRow struct {
	Date       pgtype.Date `json:"date"`
	Normal     int32       `json:"normal"`
	Suspicious int32       `json:"suspicious"`
	Malicious  int32       `json:"malicious"`
}

func (q *Queries) GetThreatTrends(ctx context.Context, arg GetThreatTrendsParams) ([]GetThreatTrendsRow, error) {
	rows, err := q.db.Query(ctx, getThreatTrends, arg.UserID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetThreatTrendsRow{}
	for rows.Next() {
		var i GetThreatTrendsRow
		if err := rows.Scan(
			&i.Date,
			&i.Normal,
			&i.Suspicious,
			&i.Malicious,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopASNs = `-- name: GetTopASNs :many
SELECT 
    COALESCE(te.asn, 'Unknown') as asn,
    COALESCE(te.isp, 'Unknown') as isp_name,
    COALESCE(te.country, 'Unknown') as country,
    SUM(te.hit_count)::int as count,
    COUNT(DISTINCT te.source_ip)::int as unique_ips
FROM traffic_events te
JOIN servers s ON te.server_id = s.id
WHERE s.user_id = $1
  AND te.created_at >= $2
  AND te.created_at <= $3
  AND te.asn IS NOT NULL
GROUP BY te.asn, te.isp, te.country
ORDER BY count DESC
LIMIT $4
`

type GetTopASNsParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
}

type GetTopASNsRow struct {
	Asn       string `json:"asn"`
	IspName   string `json:"isp_name"`
	Country   string `json:"country"`
	Count     int32  `json:"count"`
	UniqueIps int32  `json:"unique_ips"`
}

func (q *Queries) GetTopASNs(ctx context.Context, arg GetTopASNsParams) ([]GetTopASNsRow, error) {
	rows, err := q.db.Query(ctx, getTopASNs,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopASNsRow{}
	for rows.Next() {
		var i GetTopASNsRow
		if err := rows.Scan(
			&i.Asn,
			&i.IspName,
			&i.Country,
			&i.Count,
			&i.UniqueIps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopSourceCountries = `-- name: GetTopSourceCountries :many
SELECT 
    COALESCE(te.country, 'Unknown') as country,
    COUNT(*)::int as attack_count,
    COUNT(DISTINCT te.source_ip)::int as unique_ips,
    ROUND(100.0 * COUNT(*) / SUM(COUNT(*)) OVER (), 1) as percentage
FROM traffic_events te
JOIN servers s ON te.server_id = s.id
WHERE s.user_id = $1
  AND te.created_at >= $2
  AND te.created_at <= $3
GROUP BY te.country
ORDER BY attack_count DESC
LIMIT $4
`

type GetTopSourceCountriesParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
}

type GetTopSourceCountriesRow struct {
	Country     string         `json:"country"`
	AttackCount int32          `json:"attack_count"`
	UniqueIps   int32          `json:"unique_ips"`
	Percentage  pgtype.Numeric `json:"percentage"`
}

func (q *Queries) GetTopSourceCountries(ctx context.Context, arg GetTopSourceCountriesParams) ([]GetTopSourceCountriesRow, error) {
	rows, err := q.db.Query(ctx, getTopSourceCountries,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopSourceCountriesRow{}
	for rows.Next() {
		var i GetTopSourceCountriesRow
		if err := rows.Scan(
			&i.Country,
			&i.AttackCount,
			&i.UniqueIps,
			&i.Percentage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopSourceIPs = `-- name: GetTopSourceIPs :many
SELECT 
    te.source_ip::text as ip,
    SUM(te.hit_count)::int as count,
    COUNT(DISTINCT te.destination_port)::int as unique_ports,
    MIN(te.first_seen) as first_seen,
    MAX(te.last_seen) as last_seen,
    COALESCE(te.country, 'Unknown') as country,
    COALESCE(te.isp, 'Unknown') as isp
FROM traffic_events te
JOIN servers s ON te.server_id = s.id
WHERE s.user_id = $1
  AND te.created_at >= $2
  AND te.created_at <= $3
GROUP BY te.source_ip, te.country, te.isp
ORDER BY count DESC
LIMIT $4
`

type GetTopSourceIPsParams struct {
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
	Limit       int32              `json:"limit"`
}

type GetTopSourceIPsRow struct {
	Ip          string      `json:"ip"`
	Count       int32       `json:"count"`
	UniquePorts int32       `json:"unique_ports"`
	FirstSeen   interface{} `json:"first_seen"`
	LastSeen    interface{} `json:"last_seen"`
	Country     string      `json:"country"`
	Isp         string      `json:"isp"`
}

func (q *Queries) GetTopSourceIPs(ctx context.Context, arg GetTopSourceIPsParams) ([]GetTopSourceIPsRow, error) {
	rows, err := q.db.Query(ctx, getTopSourceIPs,
		arg.UserID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTopSourceIPsRow{}
	for rows.Next() {
		var i GetTopSourceIPsRow
		if err := rows.Scan(
			&i.Ip,
			&i.Count,
			&i.UniquePorts,
			&i.FirstSeen,
			&i.LastSeen,
			&i.Country,
			&i.Isp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, plan, max_servers, created_at, updated_at, polar_customer_id, polar_subscription_id, subscription_status, subscription_current_period_start, subscription_current_period_end, subscription_cancel_at_period_end, trial_ends_at, has_used_trial, refresh_token, refresh_token_expires_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Plan,
		&i.MaxServers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PolarCustomerID,
		&i.PolarSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionCurrentPeriodStart,
		&i.SubscriptionCurrentPeriodEnd,
		&i.SubscriptionCancelAtPeriodEnd,
		&i.TrialEndsAt,
		&i.HasUsedTrial,
		&i.RefreshToken,
		&i.RefreshTokenExpiresAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, plan, max_servers, created_at, updated_at, polar_customer_id, polar_subscription_id, subscription_status, subscription_current_period_start, subscription_current_period_end, subscription_cancel_at_period_end, trial_ends_at, has_used_trial, refresh_token, refresh_token_expires_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Plan,
		&i.MaxServers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PolarCustomerID,
		&i.PolarSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionCurrentPeriodStart,
		&i.SubscriptionCurrentPeriodEnd,
		&i.SubscriptionCancelAtPeriodEnd,
		&i.TrialEndsAt,
		&i.HasUsedTrial,
		&i.RefreshToken,
		&i.RefreshTokenExpiresAt,
	)
	return i, err
}

const getUserByPolarCustomerID = `-- name: GetUserByPolarCustomerID :one

SELECT id, email, password_hash, plan, max_servers, created_at, updated_at, polar_customer_id, polar_subscription_id, subscription_status, subscription_current_period_start, subscription_current_period_end, subscription_cancel_at_period_end, trial_ends_at, has_used_trial, refresh_token, refresh_token_expires_at FROM users
WHERE polar_customer_id = $1
`

// ============================================
// User Polar Integration Queries
// ============================================
func (q *Queries) GetUserByPolarCustomerID(ctx context.Context, polarCustomerID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPolarCustomerID, polarCustomerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Plan,
		&i.MaxServers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PolarCustomerID,
		&i.PolarSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionCurrentPeriodStart,
		&i.SubscriptionCurrentPeriodEnd,
		&i.SubscriptionCancelAtPeriodEnd,
		&i.TrialEndsAt,
		&i.HasUsedTrial,
		&i.RefreshToken,
		&i.RefreshTokenExpiresAt,
	)
	return i, err
}

const getUserByRefreshToken = `-- name: GetUserByRefreshToken :one
SELECT id, email, password_hash, plan, max_servers, created_at, updated_at, polar_customer_id, polar_subscription_id, subscription_status, subscription_current_period_start, subscription_current_period_end, subscription_cancel_at_period_end, trial_ends_at, has_used_trial, refresh_token, refresh_token_expires_at FROM users
WHERE refresh_token = $1
`

func (q *Queries) GetUserByRefreshToken(ctx context.Context, refreshToken pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByRefreshToken, refreshToken)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Plan,
		&i.MaxServers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PolarCustomerID,
		&i.PolarSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionCurrentPeriodStart,
		&i.SubscriptionCurrentPeriodEnd,
		&i.SubscriptionCancelAtPeriodEnd,
		&i.TrialEndsAt,
		&i.HasUsedTrial,
		&i.RefreshToken,
		&i.RefreshTokenExpiresAt,
	)
	return i, err
}

const getUserSubscriptionStatus = `-- name: GetUserSubscriptionStatus :one
SELECT 
    u.id,
    u.email,
    u.plan,
    u.max_servers,
    u.subscription_status,
    u.subscription_current_period_start,
    u.subscription_current_period_end,
    u.subscription_cancel_at_period_end,
    u.trial_ends_at,
    p.display_name as plan_display_name,
    p.data_retention_days,
    p.features,
    (SELECT COUNT(*) FROM servers WHERE user_id = u.id) as current_server_count
FROM users u
LEFT JOIN subscription_plans p ON u.plan = p.name
WHERE u.id = $1
`

type GetUserSubscriptionStatusRow struct {
	ID                             pgtype.UUID        `json:"id"`
	Email                          string             `json:"email"`
	Plan                           string             `json:"plan"`
	MaxServers                     int32              `json:"max_servers"`
	SubscriptionStatus             pgtype.Text        `json:"subscription_status"`
	SubscriptionCurrentPeriodStart pgtype.Timestamptz `json:"subscription_current_period_start"`
	SubscriptionCurrentPeriodEnd   pgtype.Timestamptz `json:"subscription_current_period_end"`
	SubscriptionCancelAtPeriodEnd  pgtype.Bool        `json:"subscription_cancel_at_period_end"`
	TrialEndsAt                    pgtype.Timestamptz `json:"trial_ends_at"`
	PlanDisplayName                pgtype.Text        `json:"plan_display_name"`
	DataRetentionDays              pgtype.Int4        `json:"data_retention_days"`
	Features                       []byte             `json:"features"`
	CurrentServerCount             int64              `json:"current_server_count"`
}

func (q *Queries) GetUserSubscriptionStatus(ctx context.Context, id pgtype.UUID) (GetUserSubscriptionStatusRow, error) {
	row := q.db.QueryRow(ctx, getUserSubscriptionStatus, id)
	var i GetUserSubscriptionStatusRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Plan,
		&i.MaxServers,
		&i.SubscriptionStatus,
		&i.SubscriptionCurrentPeriodStart,
		&i.SubscriptionCurrentPeriodEnd,
		&i.SubscriptionCancelAtPeriodEnd,
		&i.TrialEndsAt,
		&i.PlanDisplayName,
		&i.DataRetentionDays,
		&i.Features,
		&i.CurrentServerCount,
	)
	return i, err
}

const listActivePlans = `-- name: ListActivePlans :many
SELECT id, name, display_name, description, price_cents, currency, billing_interval, max_servers, data_retention_days, features, polar_product_id, polar_price_id, is_active, is_default, created_at, updated_at FROM subscription_plans
WHERE is_active = true
ORDER BY price_cents ASC
`

func (q *Queries) ListActivePlans(ctx context.Context) ([]SubscriptionPlan, error) {
	rows, err := q.db.Query(ctx, listActivePlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionPlan{}
	for rows.Next() {
		var i SubscriptionPlan
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.BillingInterval,
			&i.MaxServers,
			&i.DataRetentionDays,
			&i.Features,
			&i.PolarProductID,
			&i.PolarPriceID,
			&i.IsActive,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT a.id, a.server_id, a.source_ip, a.threat_score, a.reason, a.severity, a.status, a.auto_blocked, a.blocked_until, a.created_at, a.acknowledged_at, a.resolved_at, s.hostname as server_hostname
FROM alerts a
JOIN servers s ON a.server_id = s.id
WHERE s.user_id = $1
ORDER BY a.created_at DESC
LIMIT $2
`

type ListAlertsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type ListAlertsRow struct {
	ID             pgtype.UUID        `json:"id"`
	ServerID       pgtype.UUID        `json:"server_id"`
	SourceIp       netip.Addr         `json:"source_ip"`
	ThreatScore    int32              `json:"threat_score"`
	Reason         string             `json:"reason"`
	Severity       string             `json:"severity"`
	Status         string             `json:"status"`
	AutoBlocked    pgtype.Bool        `json:"auto_blocked"`
	BlockedUntil   pgtype.Timestamptz `json:"blocked_until"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AcknowledgedAt pgtype.Timestamptz `json:"acknowledged_at"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	ServerHostname string             `json:"server_hostname"`
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]ListAlertsRow, error) {
	rows, err := q.db.Query(ctx, listAlerts, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlertsRow{}
	for rows.Next() {
		var i ListAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.SourceIp,
			&i.ThreatScore,
			&i.Reason,
			&i.Severity,
			&i.Status,
			&i.AutoBlocked,
			&i.BlockedUntil,
			&i.CreatedAt,
			&i.AcknowledgedAt,
			&i.ResolvedAt,
			&i.ServerHostname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersByUser = `-- name: ListServersByUser :many
SELECT id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token, config FROM servers
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListServersByUser(ctx context.Context, userID pgtype.UUID) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Hostname,
			&i.IpAddress,
			&i.ApiKey,
			&i.Status,
			&i.LastSeen,
			&i.AgentVersion,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ClientToken,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreats = `-- name: ListThreats :many
SELECT te.id, te.server_id, te.source_ip, te.destination_port, te.protocol, te.syn_count, te.ack_count, te.failed_handshakes, te.unique_ports, te.bytes_in, te.bytes_out, te.threat_score, te.threat_level, te.first_seen, te.last_seen, te.created_at, te.country, te.city, te.isp, te.hit_count, te.direction, te.destination_ip, te.asn FROM traffic_events te
JOIN servers s ON te.server_id = s.id
WHERE s.user_id = $1 
  AND te.threat_level IN ('suspicious', 'malicious')
ORDER BY te.threat_score DESC, te.last_seen DESC
LIMIT $2
`

type ListThreatsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListThreats(ctx context.Context, arg ListThreatsParams) ([]TrafficEvent, error) {
	rows, err := q.db.Query(ctx, listThreats, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficEvent{}
	for rows.Next() {
		var i TrafficEvent
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.SourceIp,
			&i.DestinationPort,
			&i.Protocol,
			&i.SynCount,
			&i.AckCount,
			&i.FailedHandshakes,
			&i.UniquePorts,
			&i.BytesIn,
			&i.BytesOut,
			&i.ThreatScore,
			&i.ThreatLevel,
			&i.FirstSeen,
			&i.LastSeen,
			&i.CreatedAt,
			&i.Country,
			&i.City,
			&i.Isp,
			&i.HitCount,
			&i.Direction,
			&i.DestinationIp,
			&i.Asn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrafficEventsByServer = `-- name: ListTrafficEventsByServer :many
SELECT id, server_id, source_ip, destination_port, protocol, syn_count, ack_count, failed_handshakes, unique_ports, bytes_in, bytes_out, threat_score, threat_level, first_seen, last_seen, created_at, country, city, isp, hit_count, direction, destination_ip, asn FROM traffic_events
WHERE server_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListTrafficEventsByServerParams struct {
	ServerID pgtype.UUID `json:"server_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListTrafficEventsByServer(ctx context.Context, arg ListTrafficEventsByServerParams) ([]TrafficEvent, error) {
	rows, err := q.db.Query(ctx, listTrafficEventsByServer, arg.ServerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrafficEvent{}
	for rows.Next() {
		var i TrafficEvent
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.SourceIp,
			&i.DestinationPort,
			&i.Protocol,
			&i.SynCount,
			&i.AckCount,
			&i.FailedHandshakes,
			&i.UniquePorts,
			&i.BytesIn,
			&i.BytesOut,
			&i.ThreatScore,
			&i.ThreatLevel,
			&i.FirstSeen,
			&i.LastSeen,
			&i.CreatedAt,
			&i.Country,
			&i.City,
			&i.Isp,
			&i.HitCount,
			&i.Direction,
			&i.DestinationIp,
			&i.Asn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServerAPIKey = `-- name: UpdateServerAPIKey :exec
UPDATE servers
SET api_key = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateServerAPIKeyParams struct {
	ID     pgtype.UUID `json:"id"`
	ApiKey pgtype.Text `json:"api_key"`
}

func (q *Queries) UpdateServerAPIKey(ctx context.Context, arg UpdateServerAPIKeyParams) error {
	_, err := q.db.Exec(ctx, updateServerAPIKey, arg.ID, arg.ApiKey)
	return err
}

const updateServerConfig = `-- name: UpdateServerConfig :exec
UPDATE servers
SET config = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateServerConfigParams struct {
	ID     pgtype.UUID `json:"id"`
	Config []byte      `json:"config"`
}

func (q *Queries) UpdateServerConfig(ctx context.Context, arg UpdateServerConfigParams) error {
	_, err := q.db.Exec(ctx, updateServerConfig, arg.ID, arg.Config)
	return err
}

const updateServerForReenrollment = `-- name: UpdateServerForReenrollment :one
UPDATE servers
SET api_key = $2,
    hostname = $3,
    client_token = $4,
    status = 'active',
    last_seen = NOW()
WHERE id = $1
RETURNING id, user_id, hostname, ip_address, api_key, status, last_seen, agent_version, metadata, created_at, updated_at, client_token, config
`

type UpdateServerForReenrollmentParams struct {
	ID          pgtype.UUID `json:"id"`
	ApiKey      pgtype.Text `json:"api_key"`
	Hostname    string      `json:"hostname"`
	ClientToken pgtype.Text `json:"client_token"`
}

func (q *Queries) UpdateServerForReenrollment(ctx context.Context, arg UpdateServerForReenrollmentParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServerForReenrollment,
		arg.ID,
		arg.ApiKey,
		arg.Hostname,
		arg.ClientToken,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Hostname,
		&i.IpAddress,
		&i.ApiKey,
		&i.Status,
		&i.LastSeen,
		&i.AgentVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClientToken,
		&i.Config,
	)
	return i, err
}

const updateServerHeartbeat = `-- name: UpdateServerHeartbeat :exec
UPDATE servers 
SET last_seen = NOW(), 
    agent_version = $1, 
    ip_address = COALESCE(ip_address, $2),
    status = 'active'
WHERE api_key = $3
`

type UpdateServerHeartbeatParams struct {
	AgentVersion pgtype.Text `json:"agent_version"`
	IpAddress    *netip.Addr `json:"ip_address"`
	ApiKey       pgtype.Text `json:"api_key"`
}

func (q *Queries) UpdateServerHeartbeat(ctx context.Context, arg UpdateServerHeartbeatParams) error {
	_, err := q.db.Exec(ctx, updateServerHeartbeat, arg.AgentVersion, arg.IpAddress, arg.ApiKey)
	return err
}

const updateServerStatus = `-- name: UpdateServerStatus :exec
UPDATE servers
SET status = $2
WHERE id = $1
`

type UpdateServerStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateServerStatus(ctx context.Context, arg UpdateServerStatusParams) error {
	_, err := q.db.Exec(ctx, updateServerStatus, arg.ID, arg.Status)
	return err
}

const updateUserPolarCustomerID = `-- name: UpdateUserPolarCustomerID :exec
UPDATE users
SET polar_customer_id = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserPolarCustomerIDParams struct {
	ID              pgtype.UUID `json:"id"`
	PolarCustomerID pgtype.Text `json:"polar_customer_id"`
}

func (q *Queries) UpdateUserPolarCustomerID(ctx context.Context, arg UpdateUserPolarCustomerIDParams) error {
	_, err := q.db.Exec(ctx, updateUserPolarCustomerID, arg.ID, arg.PolarCustomerID)
	return err
}

const updateUserRefreshToken = `-- name: UpdateUserRefreshToken :one
UPDATE users
SET refresh_token = $2,
    refresh_token_expires_at = $3
WHERE id = $1
RETURNING id, email, password_hash, plan, max_servers, created_at, updated_at, polar_customer_id, polar_subscription_id, subscription_status, subscription_current_period_start, subscription_current_period_end, subscription_cancel_at_period_end, trial_ends_at, has_used_trial, refresh_token, refresh_token_expires_at
`

type UpdateUserRefreshTokenParams struct {
	ID                    pgtype.UUID        `json:"id"`
	RefreshToken          pgtype.Text        `json:"refresh_token"`
	RefreshTokenExpiresAt pgtype.Timestamptz `json:"refresh_token_expires_at"`
}

func (q *Queries) UpdateUserRefreshToken(ctx context.Context, arg UpdateUserRefreshTokenParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRefreshToken, arg.ID, arg.RefreshToken, arg.RefreshTokenExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Plan,
		&i.MaxServers,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PolarCustomerID,
		&i.PolarSubscriptionID,
		&i.SubscriptionStatus,
		&i.SubscriptionCurrentPeriodStart,
		&i.SubscriptionCurrentPeriodEnd,
		&i.SubscriptionCancelAtPeriodEnd,
		&i.TrialEndsAt,
		&i.HasUsedTrial,
		&i.RefreshToken,
		&i.RefreshTokenExpiresAt,
	)
	return i, err
}

const updateUserSubscription = `-- name: UpdateUserSubscription :exec
UPDATE users
SET plan = $2,
    polar_customer_id = COALESCE($3, polar_customer_id),
    polar_subscription_id = COALESCE($4, polar_subscription_id),
    subscription_status = COALESCE($5, subscription_status),
    subscription_current_period_start = COALESCE($6, subscription_current_period_start),
    subscription_current_period_end = COALESCE($7, subscription_current_period_end),
    subscription_cancel_at_period_end = COALESCE($8, subscription_cancel_at_period_end),
    trial_ends_at = COALESCE($9, trial_ends_at),
    has_used_trial = COALESCE($10, has_used_trial),
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserSubscriptionParams struct {
	ID                             pgtype.UUID        `json:"id"`
	Plan                           string             `json:"plan"`
	PolarCustomerID                pgtype.Text        `json:"polar_customer_id"`
	PolarSubscriptionID            pgtype.Text        `json:"polar_subscription_id"`
	SubscriptionStatus             pgtype.Text        `json:"subscription_status"`
	SubscriptionCurrentPeriodStart pgtype.Timestamptz `json:"subscription_current_period_start"`
	SubscriptionCurrentPeriodEnd   pgtype.Timestamptz `json:"subscription_current_period_end"`
	SubscriptionCancelAtPeriodEnd  pgtype.Bool        `json:"subscription_cancel_at_period_end"`
	TrialEndsAt                    pgtype.Timestamptz `json:"trial_ends_at"`
	HasUsedTrial                   pgtype.Bool        `json:"has_used_trial"`
}

func (q *Queries) UpdateUserSubscription(ctx context.Context, arg UpdateUserSubscriptionParams) error {
	_, err := q.db.Exec(ctx, updateUserSubscription,
		arg.ID,
		arg.Plan,
		arg.PolarCustomerID,
		arg.PolarSubscriptionID,
		arg.SubscriptionStatus,
		arg.SubscriptionCurrentPeriodStart,
		arg.SubscriptionCurrentPeriodEnd,
		arg.SubscriptionCancelAtPeriodEnd,
		arg.TrialEndsAt,
		arg.HasUsedTrial,
	)
	return err
}

const updateUserTrial = `-- name: UpdateUserTrial :exec
UPDATE users
SET trial_ends_at = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserTrialParams struct {
	ID          pgtype.UUID        `json:"id"`
	TrialEndsAt pgtype.Timestamptz `json:"trial_ends_at"`
}

func (q *Queries) UpdateUserTrial(ctx context.Context, arg UpdateUserTrialParams) error {
	_, err := q.db.Exec(ctx, updateUserTrial, arg.ID, arg.TrialEndsAt)
	return err
}

const upsertTrafficEvent = `-- name: UpsertTrafficEvent :one
INSERT INTO traffic_events (
    server_id, source_ip, destination_ip, destination_port, protocol, direction,
    syn_count, ack_count, failed_handshakes, unique_ports,
    bytes_in, bytes_out, threat_score, threat_level,
    first_seen, last_seen, country, city, isp, asn, hit_count
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, 1)
ON CONFLICT (server_id, source_ip, destination_ip, destination_port, direction) DO UPDATE SET
    syn_count = traffic_events.syn_count + EXCLUDED.syn_count,
    ack_count = traffic_events.ack_count + EXCLUDED.ack_count,
    failed_handshakes = traffic_events.failed_handshakes + EXCLUDED.failed_handshakes,
    unique_ports = GREATEST(traffic_events.unique_ports, EXCLUDED.unique_ports),
    bytes_in = traffic_events.bytes_in + EXCLUDED.bytes_in,
    bytes_out = traffic_events.bytes_out + EXCLUDED.bytes_out,
    threat_score = GREATEST(traffic_events.threat_score, EXCLUDED.threat_score),
    threat_level = CASE 
        WHEN EXCLUDED.threat_score > traffic_events.threat_score THEN EXCLUDED.threat_level 
        ELSE traffic_events.threat_level 
    END,
    last_seen = EXCLUDED.last_seen,
    hit_count = traffic_events.hit_count + 1
RETURNING id, server_id, source_ip, destination_port, protocol, syn_count, ack_count, failed_handshakes, unique_ports, bytes_in, bytes_out, threat_score, threat_level, first_seen, last_seen, created_at, country, city, isp, hit_count, direction, destination_ip, asn
`

type UpsertTrafficEventParams struct {
	ServerID         pgtype.UUID        `json:"server_id"`
	SourceIp         netip.Addr         `json:"source_ip"`
	DestinationIp    *netip.Addr        `json:"destination_ip"`
	DestinationPort  int32              `json:"destination_port"`
	Protocol         string             `json:"protocol"`
	Direction        string             `json:"direction"`
	SynCount         int32              `json:"syn_count"`
	AckCount         int32              `json:"ack_count"`
	FailedHandshakes int32              `json:"failed_handshakes"`
	UniquePorts      int32              `json:"unique_ports"`
	BytesIn          int64              `json:"bytes_in"`
	BytesOut         int64              `json:"bytes_out"`
	ThreatScore      int32              `json:"threat_score"`
	ThreatLevel      string             `json:"threat_level"`
	FirstSeen        pgtype.Timestamptz `json:"first_seen"`
	LastSeen         pgtype.Timestamptz `json:"last_seen"`
	Country          pgtype.Text        `json:"country"`
	City             pgtype.Text        `json:"city"`
	Isp              pgtype.Text        `json:"isp"`
	Asn              pgtype.Text        `json:"asn"`
}

func (q *Queries) UpsertTrafficEvent(ctx context.Context, arg UpsertTrafficEventParams) (TrafficEvent, error) {
	row := q.db.QueryRow(ctx, upsertTrafficEvent,
		arg.ServerID,
		arg.SourceIp,
		arg.DestinationIp,
		arg.DestinationPort,
		arg.Protocol,
		arg.Direction,
		arg.SynCount,
		arg.AckCount,
		arg.FailedHandshakes,
		arg.UniquePorts,
		arg.BytesIn,
		arg.BytesOut,
		arg.ThreatScore,
		arg.ThreatLevel,
		arg.FirstSeen,
		arg.LastSeen,
		arg.Country,
		arg.City,
		arg.Isp,
		arg.Asn,
	)
	var i TrafficEvent
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.SourceIp,
		&i.DestinationPort,
		&i.Protocol,
		&i.SynCount,
		&i.AckCount,
		&i.FailedHandshakes,
		&i.UniquePorts,
		&i.BytesIn,
		&i.BytesOut,
		&i.ThreatScore,
		&i.ThreatLevel,
		&i.FirstSeen,
		&i.LastSeen,
		&i.CreatedAt,
		&i.Country,
		&i.City,
		&i.Isp,
		&i.HitCount,
		&i.Direction,
		&i.DestinationIp,
		&i.Asn,
	)
	return i, err
}
