#!/bin/sh
# KernelEye Frontend Entrypoint Script
# Serves static files for landing page and dashboard

set -e

# ==========================================
# Environment Variables with Defaults
# ==========================================

# Backend API configuration (for dashboard runtime config)
# Production: https://api.kerneleye.cloud/api/v1
# Development: https://kerneleyeapi.hakiware.com/api/v1
export BACKEND_HOST="${BACKEND_HOST:-api.kerneleye.cloud}"
export BACKEND_PORT="${BACKEND_PORT:-443}"

# Domain configuration
export LANDING_DOMAIN="${LANDING_DOMAIN:-kerneleye.cloud}"
export DASHBOARD_DOMAIN="${DASHBOARD_DOMAIN:-app.kerneleye.cloud}"

# Construct API URL for dashboard
if [ "$BACKEND_PORT" = "443" ]; then
    export API_URL="https://${BACKEND_HOST}/api/v1"
    export WS_URL="wss://${BACKEND_HOST}/ws"
else
    export API_URL="http://${BACKEND_HOST}:${BACKEND_PORT}/api/v1"
    export WS_URL="ws://${BACKEND_HOST}:${BACKEND_PORT}/ws"
fi

# ==========================================
# Logging Configuration
# ==========================================

echo "=========================================="
echo "KernelEye Frontend Configuration"
echo "=========================================="
echo "Landing Domain:   $LANDING_DOMAIN"
echo "Dashboard Domain: $DASHBOARD_DOMAIN"
echo "API URL:          $API_URL"
echo "WebSocket URL:    $WS_URL"
echo "=========================================="

# ==========================================
# Generate Nginx Config
# ==========================================

# Process nginx template
envsubst '\$LANDING_DOMAIN \$DASHBOARD_DOMAIN' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf

echo "Nginx configuration generated"

# ==========================================
# Generate Runtime Config for Dashboard
# ==========================================

# Create runtime config JS that the dashboard can load
cat > /usr/share/nginx/html/dashboard/config/runtime-config.js << EOF
// Runtime configuration generated by entrypoint script
window.KERNELEYE_CONFIG = {
  API_URL: "${API_URL}",
  WS_URL: "${WS_URL}",
  ENV: "production"
};
console.log('[KernelEye] Runtime config loaded:', window.KERNELEYE_CONFIG);
EOF

echo "Dashboard runtime config generated"

# ==========================================
# Start Nginx
# ==========================================

echo "Starting nginx..."
exec "$@"
