#!/bin/sh
# KernelEye Frontend Entrypoint Script
# Configures nginx and runtime environment for landing page + dashboard

set -e

# ==========================================
# Environment Variables with Defaults
# ==========================================

# Backend API configuration
# Production: api.kerneleye.cloud
# Development: kerneleyeapi.hakiware.com
export BACKEND_HOST="${BACKEND_HOST:-api.kerneleye.cloud}"
export BACKEND_PORT="${BACKEND_PORT:-443}"

# Domain configuration
export LANDING_DOMAIN="${LANDING_DOMAIN:-kerneleye.cloud}"
export DASHBOARD_DOMAIN="${DASHBOARD_DOMAIN:-app.kerneleye.cloud}"

# API URL for dashboard (constructed from backend config)
if [ "$BACKEND_PORT" = "443" ]; then
    export API_URL="https://${BACKEND_HOST}/api/v1"
else
    export API_URL="http://${BACKEND_HOST}:${BACKEND_PORT}/api/v1"
fi

# ==========================================
# Logging Configuration
# ==========================================

echo "=========================================="
echo "KernelEye Frontend Configuration"
echo "=========================================="
echo "Landing Domain:  $LANDING_DOMAIN"
echo "Dashboard Domain: $DASHBOARD_DOMAIN"
echo "Backend Host:    $BACKEND_HOST"
echo "Backend Port:    $BACKEND_PORT"
echo "API URL:         $API_URL"
echo "=========================================="

# ==========================================
# Generate Nginx Config
# ==========================================

# Process nginx template
envsubst '\$LANDING_DOMAIN \$DASHBOARD_DOMAIN \$BACKEND_HOST \$BACKEND_PORT' < /etc/nginx/templates/default.conf.template > /etc/nginx/conf.d/default.conf

echo "Nginx configuration generated"

# ==========================================
# Generate Runtime Config for Dashboard
# ==========================================

# Create runtime config JS that the dashboard can load
cat > /usr/share/nginx/html/dashboard/config/runtime-config.js << EOF
// Runtime configuration generated by entrypoint script
window.KERNELEYE_CONFIG = {
  API_URL: "${API_URL}",
  WS_URL: "wss://${BACKEND_HOST}/ws",
  ENV: "${NODE_ENV:-production}"
};
EOF

echo "Dashboard runtime config generated"

# ==========================================
# Replace API URL in built JS files (fallback)
# ==========================================

# Find and replace placeholder API URLs in the dashboard build
# This handles the case where the app was built with a different URL
if [ -d "/usr/share/nginx/html/dashboard/assets" ]; then
    # Replace common placeholder URLs
    find /usr/share/nginx/html/dashboard/assets -name "*.js" -exec \
        sed -i "s|http://localhost:8080/api/v1|${API_URL}|g" {} \;
    
    find /usr/share/nginx/html/dashboard/assets -name "*.js" -exec \
        sed -i "s|/api/v1|${API_URL}|g" {} \;
    
    echo "Dashboard JS files patched with API URL"
fi

# ==========================================
# Start Nginx
# ==========================================

echo "Starting nginx..."
exec "$@"
