// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfConnKey struct {
	Saddr uint32
	Daddr uint32
	Sport uint16
	Dport uint16
}

type bpfConnKeyV6 struct {
	Saddr bpfIn6Addr
	Daddr bpfIn6Addr
	Sport uint16
	Dport uint16
}

type bpfIn6Addr struct{ In6U struct{ U6Addr8 [16]uint8 } }

type bpfIpBytes struct {
	BytesIn  uint64
	BytesOut uint64
}

type bpfRateLimitState struct {
	WindowStart  uint64
	EventCount   uint32
	DroppedCount uint32
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	DetectInboundSyn     *ebpf.ProgramSpec `ebpf:"detect_inbound_syn"`
	DetectTcpAccept      *ebpf.ProgramSpec `ebpf:"detect_tcp_accept"`
	DetectTcpClose       *ebpf.ProgramSpec `ebpf:"detect_tcp_close"`
	DetectTcpConnRequest *ebpf.ProgramSpec `ebpf:"detect_tcp_conn_request"`
	DetectTcpConnect     *ebpf.ProgramSpec `ebpf:"detect_tcp_connect"`
	DetectTcpStateChange *ebpf.ProgramSpec `ebpf:"detect_tcp_state_change"`
	DetectUdpRecv        *ebpf.ProgramSpec `ebpf:"detect_udp_recv"`
	TcEgress             *ebpf.ProgramSpec `ebpf:"tc_egress"`
	TcIngress            *ebpf.ProgramSpec `ebpf:"tc_ingress"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events           *ebpf.MapSpec `ebpf:"events"`
	IpByteCounters   *ebpf.MapSpec `ebpf:"ip_byte_counters"`
	IpByteCountersV6 *ebpf.MapSpec `ebpf:"ip_byte_counters_v6"`
	RateLimiter      *ebpf.MapSpec `ebpf:"rate_limiter"`
	TcpSynTracker    *ebpf.MapSpec `ebpf:"tcp_syn_tracker"`
	TcpSynTrackerV6  *ebpf.MapSpec `ebpf:"tcp_syn_tracker_v6"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events           *ebpf.Map `ebpf:"events"`
	IpByteCounters   *ebpf.Map `ebpf:"ip_byte_counters"`
	IpByteCountersV6 *ebpf.Map `ebpf:"ip_byte_counters_v6"`
	RateLimiter      *ebpf.Map `ebpf:"rate_limiter"`
	TcpSynTracker    *ebpf.Map `ebpf:"tcp_syn_tracker"`
	TcpSynTrackerV6  *ebpf.Map `ebpf:"tcp_syn_tracker_v6"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.IpByteCounters,
		m.IpByteCountersV6,
		m.RateLimiter,
		m.TcpSynTracker,
		m.TcpSynTrackerV6,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	DetectInboundSyn     *ebpf.Program `ebpf:"detect_inbound_syn"`
	DetectTcpAccept      *ebpf.Program `ebpf:"detect_tcp_accept"`
	DetectTcpClose       *ebpf.Program `ebpf:"detect_tcp_close"`
	DetectTcpConnRequest *ebpf.Program `ebpf:"detect_tcp_conn_request"`
	DetectTcpConnect     *ebpf.Program `ebpf:"detect_tcp_connect"`
	DetectTcpStateChange *ebpf.Program `ebpf:"detect_tcp_state_change"`
	DetectUdpRecv        *ebpf.Program `ebpf:"detect_udp_recv"`
	TcEgress             *ebpf.Program `ebpf:"tc_egress"`
	TcIngress            *ebpf.Program `ebpf:"tc_ingress"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.DetectInboundSyn,
		p.DetectTcpAccept,
		p.DetectTcpClose,
		p.DetectTcpConnRequest,
		p.DetectTcpConnect,
		p.DetectTcpStateChange,
		p.DetectUdpRecv,
		p.TcEgress,
		p.TcIngress,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel_x86.o
var _BpfBytes []byte
