const Privacy = () => {
  return (
    <div style={{ minHeight: '100vh', padding: '6rem 2rem 4rem', background: 'var(--color-bg)' }}>
      <div style={{ maxWidth: 800, margin: '0 auto' }}>
        <h1 style={{ fontSize: '2.5rem', fontWeight: 700, marginBottom: '1rem', color: 'var(--color-text)' }}>
          Privacy Policy
        </h1>
        <p style={{ color: 'var(--color-text-muted)', marginBottom: '3rem' }}>
          Last updated: February 2026
        </p>

        <div style={{ color: 'var(--color-text-secondary)', lineHeight: 1.8, display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          <section>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text)' }}>
              1. Introduction
            </h2>
            <p>
              At KernelEye, we take your privacy seriously. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our security monitoring service.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text)' }}>
              2. Information We Collect
            </h2>
            <p>
              We collect information that you provide directly to us, including:
            </p>
            <ul style={{ marginLeft: '1.5rem', marginTop: '0.5rem' }}>
              <li>Account information (name, email, company)</li>
              <li>Authentication data from OAuth providers</li>
              <li>Server configuration data you choose to monitor</li>
              <li>Security logs and alerts generated by our service</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text)' }}>
              3. How We Use Your Information
            </h2>
            <p>
              We use the information we collect to:
            </p>
            <ul style={{ marginLeft: '1.5rem', marginTop: '0.5rem' }}>
              <li>Provide and maintain our security monitoring services</li>
              <li>Detect and respond to security threats</li>
              <li>Send you alerts and notifications about your servers</li>
              <li>Improve and optimize our service</li>
              <li>Communicate with you about updates and support</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text)' }}>
              4. Data Security
            </h2>
            <p>
              We implement appropriate technical and organizational measures to protect your personal data against unauthorized access, alteration, disclosure, or destruction. All data is encrypted in transit and at rest.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text)' }}>
              5. Data Retention
            </h2>
            <p>
              We retain your personal information for as long as your account is active or as needed to provide you services. You can request deletion of your data at any time by contacting support@kerneleye.com
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text)' }}>
              6. Third-Party Services
            </h2>
            <p>
              We may share your information with third-party service providers who assist us in operating our service. These providers are obligated to maintain the confidentiality of your information and are restricted from using it for any other purpose.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text)' }}>
              7. Your Rights
            </h2>
            <p>
              You have the right to:
            </p>
            <ul style={{ marginLeft: '1.5rem', marginTop: '0.5rem' }}>
              <li>Access your personal information</li>
              <li>Correct inaccurate data</li>
              <li>Request deletion of your data</li>
              <li>Object to processing of your data</li>
              <li>Export your data in a portable format</li>
            </ul>
          </section>

          <section>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text)' }}>
              8. Cookies
            </h2>
            <p>
              We use cookies and similar tracking technologies to enhance your experience. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text)' }}>
              9. Changes to This Policy
            </h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date.
            </p>
          </section>

          <section>
            <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1rem', color: 'var(--color-text)' }}>
              10. Contact Us
            </h2>
            <p>
              If you have any questions about this Privacy Policy, please contact us at support@kerneleye.com
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};

export default Privacy;
